/**
 * Vertical de demonstração — saúde (Clínica Vitalis).
 *
 * O que esta base demonstra e as outras não: **dado sensível como regra de
 * operação, não como aviso jurídico**. Aqui o campo personalizado marcado como
 * sensível muda o que a IA recebe, o consentimento é por finalidade e o Inbox
 * lida com informação que não pode aparecer em contexto de modelo.
 *
 * O segundo eixo é a **agenda**: no e-commerce o gargalo é volume; aqui é
 * horário. Confirmação, remarcação e falta são o ciclo inteiro, e o valor do
 * produto aparece na taxa de comparecimento, não no tempo de resposta.
 */

import type { DemoOverlay, DemoVerticalMeta } from "../types";
import type { Pipeline, Tag } from "../../types/crm";
import type { CannedResponse } from "../../types/inbox";
import type { MessageTemplate, Segment } from "../../types/marketing";
import type { Organization, Team } from "../../types/organization";
import { ORG_ID } from "../../mock/organization";
import { offsetIso } from "../../utils/datetime";
import {
  buildCampaigns,
  buildChannelAccounts,
  buildClosingReasons,
  buildCompanies,
  buildContacts,
  buildConversations,
  buildCustomFields,
  buildDeals,
  buildQueues,
  buildSkills,
  buildTasks,
  buildTimeline,
  buildUsers,
} from "../build";

const BRAND = "Clínica Vitalis";

export const CLINICA_META: DemoVerticalMeta = {
  id: "clinica",
  name: "Saúde",
  company: BRAND,
  tagline: "Clínica multiespecialidade com três unidades",
  description:
    "Agendamento, confirmação, remarcação e retorno. É a base onde a minimização de dado importa " +
    "de verdade: informação clínica não entra no contexto do modelo, e o produto continua " +
    "funcionando — inclusive a proposta de tabulação.",
  hue: 262,
  highlights: [
    "Campo sensível fica fora do contexto da IA — presença, nunca conteúdo.",
    "Régua de confirmação em 48 h e 3 h, com remarcação em um toque.",
    "Consentimento por finalidade: atendimento, cobrança e marketing separados.",
  ],
  channels: ["whatsapp", "webchat", "email", "phone"],
  stats: [
    { label: "Agendamentos / mês", value: "5,2 mil" },
    { label: "Taxa de falta", value: "7,4%" },
    { label: "Confirmação automática", value: "83%" },
  ],
};

const organization: Organization = {
  id: ORG_ID,
  name: BRAND,
  slug: "clinica-vitalis",
  brandColor: "#18181B",
  timezone: "America/Sao_Paulo",
};

const teams: Team[] = [
  { id: "team_atendimento", organizationId: ORG_ID, name: "Recepção e agendamento" },
  { id: "team_comercial", organizationId: ORG_ID, name: "Convênios e particulares" },
  { id: "team_marketing", organizationId: ORG_ID, name: "Marketing e relacionamento" },
  { id: "team_aluno", organizationId: ORG_ID, name: "Pós-consulta e exames" },
];

const skills = buildSkills(ORG_ID, [
  {
    key: "agendamento",
    label: "Agendamento",
    description: "Marcação, remarcação e encaixe de agenda.",
    hue: 262,
  },
  {
    key: "convenio",
    label: "Convênios",
    description: "Elegibilidade, autorização e carência.",
    hue: 200,
  },
  {
    key: "exames",
    label: "Exames",
    description: "Preparo, coleta, prazo e entrega de laudo.",
    hue: 160,
  },
  {
    key: "faturamento",
    label: "Faturamento",
    description: "Cobrança particular, reembolso e nota fiscal.",
    hue: 30,
  },
  {
    key: "urgencia",
    label: "Triagem de urgência",
    description: "Prioridade clínica e encaminhamento imediato.",
    hue: 0,
  },
]);

const queues = buildQueues(ORG_ID, [
  {
    id: "queue_matriculas",
    name: "Agendamento e remarcação",
    description: "Marcar, remarcar, cancelar e confirmar consulta ou exame.",
    channels: ["whatsapp", "webchat", "phone"],
    teamId: "team_atendimento",
    firstResponseSlaMinutes: 5,
    resolutionSlaMinutes: 120,
    color: "262",
    scheduleId: "sched_estendido",
    distribution: {
      model: "menor_carga",
      tiebreak: "menor_carga",
      delivery: "direta",
      pauseOutsideSchedule: true,
    },
  },
  {
    id: "queue_fiscal",
    name: "Convênios e autorizações",
    description: "Elegibilidade, guia, senha de autorização e carência.",
    channels: ["whatsapp", "email"],
    teamId: "team_comercial",
    firstResponseSlaMinutes: 20,
    resolutionSlaMinutes: 480,
    color: "200",
    distribution: {
      model: "habilidade",
      tiebreak: "menor_carga",
      delivery: "oferta",
      offerTimeoutSeconds: 60,
      requiredSkills: ["convenio"],
    },
  },
  {
    id: "queue_regularizacao",
    name: "Resultados e laudos",
    description: "Prazo de exame, retirada de laudo e envio ao médico solicitante.",
    channels: ["whatsapp", "email", "webchat"],
    teamId: "team_aluno",
    firstResponseSlaMinutes: 30,
    resolutionSlaMinutes: 720,
    color: "160",
    scheduleId: "sched_estendido",
    distribution: {
      model: "proprietario",
      tiebreak: "menor_carga",
      delivery: "direta",
      requireAvailable: false,
    },
  },
  {
    id: "queue_comercial",
    name: "Primeira consulta — particular",
    description: "Interessados em atendimento particular, pacotes e check-up.",
    channels: ["whatsapp", "webchat", "instagram"],
    teamId: "team_comercial",
    firstResponseSlaMinutes: 10,
    resolutionSlaMinutes: 240,
    color: "30",
    distribution: {
      model: "roleta",
      tiebreak: "roleta",
      delivery: "oferta",
      offerTimeoutSeconds: 40,
      maxOffers: 3,
    },
  },
]);

const channelAccounts = buildChannelAccounts(ORG_ID, [
  {
    id: "chan_wa_atendimento",
    kind: "whatsapp",
    label: "WhatsApp Recepção",
    address: "+554133220900",
    queueId: "queue_matriculas",
    qualityRating: "alta",
    dailyLimit: 20000,
    sentToday: 3980,
  },
  {
    id: "chan_wa_comercial",
    kind: "whatsapp",
    label: "WhatsApp Particulares",
    address: "+554133220910",
    queueId: "queue_comercial",
    qualityRating: "alta",
    dailyLimit: 10000,
    sentToday: 610,
  },
  {
    id: "chan_email_atendimento",
    kind: "email",
    label: "contato@clinicavitalis.com.br",
    address: "contato@clinicavitalis.com.br",
    queueId: "queue_regularizacao",
  },
  {
    id: "chan_instagram",
    kind: "instagram",
    label: "@clinicavitalis",
    address: "clinicavitalis",
    queueId: "queue_comercial",
  },
]);

const tags: Tag[] = [
  { id: "tag_convenio", name: "Convênio", hue: 200 },
  { id: "tag_particular", name: "Particular", hue: 30 },
  { id: "tag_retorno", name: "Retorno", hue: 160 },
  { id: "tag_falta", name: "Faltou", hue: 0 },
  { id: "tag_primeira_consulta", name: "Primeira consulta", hue: 100 },
  { id: "tag_exame", name: "Exame", hue: 262 },
  { id: "tag_idoso", name: "Prioridade legal", hue: 45 },
  { id: "tag_checkup", name: "Check-up", hue: 174 },
  { id: "tag_urgente", name: "Urgente", hue: 12 },
  { id: "tag_inadimplente", name: "Pendência financeira", hue: 340 },
];

const closingReasons = buildClosingReasons(ORG_ID, [
  {
    key: "agendado",
    label: "Consulta agendada",
    description: "Horário reservado e confirmado com o paciente.",
    resolved: true,
  },
  {
    key: "remarcado",
    label: "Remarcado",
    description: "Paciente transferido para novo horário.",
    resolved: true,
  },
  {
    key: "autorizacao_liberada",
    label: "Autorização liberada",
    description: "Senha do convênio emitida e informada.",
    resolved: true,
  },
  {
    key: "laudo_entregue",
    label: "Laudo entregue",
    description: "Resultado disponibilizado ao paciente ou ao solicitante.",
    resolved: true,
  },
  {
    key: "sem_vaga",
    label: "Sem vaga na agenda",
    description: "Paciente entrou na fila de espera por encaixe.",
    resolved: false,
    requiresNote: true,
  },
  {
    key: "desistiu",
    label: "Paciente desistiu",
    description: "Sem interesse em prosseguir com o agendamento.",
    resolved: false,
  },
]);

const customFields = buildCustomFields(ORG_ID, [
  {
    key: "convenio",
    label: "Convênio",
    description: "Operadora e plano do paciente.",
    entity: "contato",
    type: "selecao",
    options: ["Particular", "Unimed", "Bradesco Saúde", "SulAmérica", "Amil"],
  },
  {
    key: "carteirinha",
    label: "Número da carteirinha",
    description: "Identificação do beneficiário na operadora.",
    entity: "contato",
    type: "texto",
    sensitive: true,
  },
  {
    key: "observacao_clinica",
    label: "Observação clínica",
    description:
      "Anotação da recepção sobre restrição, preparo ou necessidade de acompanhante. Marcado como " +
      "sensível: a IA sabe que o campo existe e está preenchido, nunca o que ele diz.",
    entity: "contato",
    type: "texto",
    sensitive: true,
  },
  {
    key: "unidade_preferida",
    label: "Unidade preferida",
    description: "Unidade em que o paciente costuma ser atendido.",
    entity: "contato",
    type: "selecao",
    options: ["Batel", "Água Verde", "São José dos Pinhais"],
  },
]);

const cannedResponses: CannedResponse[] = [
  {
    id: "canned_confirmacao",
    organizationId: ORG_ID,
    shortcut: "/confirma",
    title: "Confirmação de consulta",
    body: "Olá, {{contato.primeiro_nome}}! Confirmando sua consulta com {{consulta.profissional}} em {{consulta.data}}, na unidade {{consulta.unidade}}. Posso confirmar?",
    channels: ["whatsapp", "webchat"],
  },
  {
    id: "canned_preparo",
    organizationId: ORG_ID,
    shortcut: "/preparo",
    title: "Preparo de exame",
    body: "Para este exame é necessário jejum de 8 horas e trazer o pedido médico. Água pode, à vontade.",
    channels: ["whatsapp", "email", "webchat"],
  },
  {
    id: "canned_autorizacao",
    organizationId: ORG_ID,
    shortcut: "/autorizacao",
    title: "Autorização do convênio",
    body: "Sua guia foi enviada à operadora. O prazo de retorno é de até 5 dias úteis e eu aviso assim que a senha sair.",
    channels: ["whatsapp", "email"],
  },
  {
    id: "canned_remarcar",
    organizationId: ORG_ID,
    shortcut: "/remarcar",
    title: "Remarcação",
    body: "Sem problema. Tenho estes horários disponíveis: {{agenda.opcoes}}. Qual fica melhor para você?",
    channels: ["whatsapp", "webchat"],
  },
  {
    id: "canned_laudo",
    organizationId: ORG_ID,
    shortcut: "/laudo",
    title: "Retirada de laudo",
    body: "Seu resultado já está disponível no portal do paciente. Se preferir a via impressa, retiramos na recepção até as 19h.",
    channels: ["whatsapp", "email", "webchat"],
  },
];

const users = buildUsers(ORG_ID, [
  {
    id: "usr_alex",
    name: "Eduardo Kraus",
    email: "eduardo.kraus@clinicavitalis.com.br",
    role: "admin_empresa",
    teamIds: ["team_atendimento", "team_comercial"],
    presence: "disponivel",
    capacity: 5,
    hue: 262,
    skills: ["agendamento", "convenio"],
  },
  {
    id: "usr_marina",
    name: "Marina Duarte",
    email: "marina.duarte@clinicavitalis.com.br",
    role: "gestor_atendimento",
    teamIds: ["team_atendimento", "team_aluno"],
    presence: "disponivel",
    capacity: 6,
    hue: 30,
    skills: ["agendamento", "urgencia"],
  },
  {
    id: "usr_rafael",
    name: "Thiago Beraldo",
    email: "thiago.beraldo@clinicavitalis.com.br",
    role: "atendente",
    teamIds: ["team_atendimento"],
    presence: "disponivel",
    capacity: 8,
    hue: 200,
    skills: ["agendamento", "exames"],
    scheduleId: "sched_estendido",
  },
  {
    id: "usr_juliana",
    name: "Silvana Ito",
    email: "silvana.ito@clinicavitalis.com.br",
    role: "atendente",
    teamIds: ["team_comercial"],
    presence: "ocupado",
    capacity: 6,
    hue: 160,
    skills: ["convenio", "faturamento"],
    acceptingNew: false,
  },
  {
    id: "usr_bruno",
    name: "Rodrigo Assaf",
    email: "rodrigo.assaf@clinicavitalis.com.br",
    role: "gestor_comercial",
    teamIds: ["team_comercial"],
    presence: "disponivel",
    capacity: 5,
    hue: 45,
    skills: ["convenio"],
  },
  {
    id: "usr_carla",
    name: "Helena Vasques",
    email: "helena.vasques@clinicavitalis.com.br",
    role: "marketing",
    teamIds: ["team_marketing"],
    presence: "ausente",
    capacity: 3,
    hue: 340,
    skills: [],
  },
  {
    id: "usr_diego",
    name: "Paulo Menegatti",
    email: "paulo.menegatti@clinicavitalis.com.br",
    role: "atendente",
    teamIds: ["team_aluno"],
    presence: "offline",
    capacity: 8,
    hue: 100,
    skills: ["exames"],
    scheduleId: "sched_estendido",
  },
]);

const companies = buildCompanies(ORG_ID, [
  {
    id: "cmp_001",
    name: "Unimed Curitiba",
    document: "75.055.332/0001-80",
    segment: "Operadora de saúde",
    city: "Curitiba",
    state: "PR",
    contactsCount: 3,
    createdDays: 700,
    updatedDays: 3,
  },
  {
    id: "cmp_002",
    name: "Metalúrgica Paraná Sul",
    document: "44.882.100/0001-32",
    segment: "Indústria — contrato PJ",
    city: "São José dos Pinhais",
    state: "PR",
    contactsCount: 2,
    createdDays: 300,
    updatedDays: 6,
  },
  {
    id: "cmp_003",
    name: "Colégio Santa Inês",
    document: "19.203.775/0001-11",
    segment: "Educação — contrato PJ",
    city: "Curitiba",
    state: "PR",
    contactsCount: 2,
    createdDays: 210,
    updatedDays: 12,
  },
  {
    id: "cmp_004",
    name: "Transportes Iguaçu",
    document: "62.114.908/0001-27",
    segment: "Logística — exame ocupacional",
    city: "Curitiba",
    state: "PR",
    contactsCount: 1,
    createdDays: 150,
    updatedDays: 2,
  },
  {
    id: "cmp_005",
    name: "SulAmérica Saúde",
    document: "01.685.053/0001-56",
    segment: "Operadora de saúde",
    city: "São Paulo",
    state: "SP",
    contactsCount: 1,
    createdDays: 620,
    updatedDays: 30,
  },
  {
    id: "cmp_006",
    name: "Cooperativa Agro Verde",
    document: "83.771.220/0001-09",
    segment: "Agronegócio — contrato PJ",
    city: "Ponta Grossa",
    state: "PR",
    contactsCount: 1,
    createdDays: 90,
    updatedDays: 8,
  },
]);

const contacts = buildContacts(ORG_ID, BRAND, [
  {
    id: "cnt_001",
    name: "Neide Comparin",
    email: "neide.comparin@gmail.com",
    phone: "+5541996330011",
    ownerId: "usr_marina",
    stage: "cliente",
    score: 74,
    origin: "whatsapp",
    city: "Curitiba",
    state: "PR",
    tags: ["tag_convenio", "tag_idoso"],
    hue: 45,
    lastDays: 0,
    createdDays: 900,
    fields: [
      { key: "convenio", label: "Convênio", value: "Unimed" },
      { key: "unidade_preferida", label: "Unidade preferida", value: "Batel" },
      {
        key: "observacao_clinica",
        label: "Observação clínica",
        value: "Preenchido — visível apenas ao time clínico",
      },
    ],
  },
  {
    id: "cnt_002",
    name: "Gustavo Perotto",
    email: "gustavo.perotto@outlook.com",
    phone: "+5541994120087",
    ownerId: "usr_rafael",
    stage: "cliente",
    score: 52,
    origin: "webchat",
    city: "Curitiba",
    state: "PR",
    tags: ["tag_exame"],
    hue: 262,
    lastDays: 0,
    createdDays: 220,
    fields: [{ key: "convenio", label: "Convênio", value: "Bradesco Saúde" }],
  },
  {
    id: "cnt_003",
    name: "Andréa Locatelli",
    email: "andrea.locatelli@gmail.com",
    phone: "+5541988770145",
    ownerId: "usr_juliana",
    stage: "cliente",
    score: 61,
    origin: "whatsapp",
    city: "São José dos Pinhais",
    state: "PR",
    tags: ["tag_convenio", "tag_retorno"],
    hue: 200,
    lastDays: 0,
    createdDays: 480,
  },
  {
    id: "cnt_004",
    name: "Wilson Nakata",
    email: "wilson.nakata@paranasul.ind.br",
    phone: "+5541993410077",
    jobTitle: "Gerente de RH",
    companyId: "cmp_002",
    ownerId: "usr_bruno",
    stage: "cliente",
    score: 83,
    origin: "email",
    city: "São José dos Pinhais",
    state: "PR",
    tags: ["tag_particular"],
    hue: 160,
    lastDays: 1,
    createdDays: 300,
  },
  {
    id: "cnt_005",
    name: "Fabiana Ceccon",
    email: "fabiana.ceccon@gmail.com",
    phone: "+5541984120033",
    ownerId: "usr_marina",
    stage: "lead_qualificado",
    score: 66,
    origin: "instagram",
    campaign: "Instagram — check-up executivo",
    city: "Curitiba",
    state: "PR",
    tags: ["tag_checkup", "tag_particular"],
    hue: 30,
    lastDays: 0,
    createdDays: 4,
  },
  {
    id: "cnt_006",
    name: "Osvaldo Brandt",
    email: "osvaldo.brandt@gmail.com",
    phone: "+5541995870021",
    ownerId: "usr_diego",
    stage: "cliente",
    score: 38,
    origin: "phone",
    city: "Curitiba",
    state: "PR",
    tags: ["tag_falta", "tag_idoso"],
    hue: 12,
    lastDays: 2,
    createdDays: 400,
  },
  {
    id: "cnt_007",
    name: "Larissa Kuhn",
    email: "larissa.kuhn@santaines.edu.br",
    phone: "+5541987660019",
    jobTitle: "Coordenadora",
    companyId: "cmp_003",
    ownerId: "usr_bruno",
    stage: "oportunidade",
    score: 70,
    origin: "form",
    campaign: "Programa saúde corporativa",
    city: "Curitiba",
    state: "PR",
    tags: ["tag_particular"],
    hue: 100,
    lastDays: 1,
    createdDays: 40,
  },
  {
    id: "cnt_008",
    name: "Márcio Bandeira",
    email: "marcio.bandeira@transportesiguacu.com.br",
    phone: "+5541991200064",
    jobTitle: "Segurança do trabalho",
    companyId: "cmp_004",
    ownerId: "usr_bruno",
    stage: "cliente",
    score: 58,
    origin: "whatsapp",
    city: "Curitiba",
    state: "PR",
    tags: ["tag_exame"],
    hue: 174,
    lastDays: 2,
    createdDays: 150,
  },
  {
    id: "cnt_009",
    name: "Simone Grzybowski",
    email: "simone.grz@gmail.com",
    phone: "+5541994520188",
    ownerId: "usr_juliana",
    stage: "cliente",
    score: 47,
    origin: "whatsapp",
    city: "Colombo",
    state: "PR",
    tags: ["tag_inadimplente"],
    hue: 340,
    lastDays: 3,
    createdDays: 260,
  },
  {
    id: "cnt_010",
    name: "Renan Piccoli",
    email: "renan.piccoli@gmail.com",
    phone: "+5541988110052",
    ownerId: "usr_rafael",
    stage: "lead",
    score: 24,
    origin: "webchat",
    campaign: "Google Ads — dermatologia",
    city: "Curitiba",
    state: "PR",
    tags: ["tag_primeira_consulta"],
    hue: 218,
    lastDays: 1,
    createdDays: 2,
  },
  {
    id: "cnt_011",
    name: "Terezinha Alcântara",
    email: "terezinha.alcantara@gmail.com",
    phone: "+5541993330091",
    ownerId: "usr_marina",
    stage: "cliente",
    score: 80,
    origin: "phone",
    city: "Curitiba",
    state: "PR",
    tags: ["tag_idoso", "tag_retorno"],
    hue: 45,
    lastDays: 0,
    createdDays: 1200,
  },
  {
    id: "cnt_012",
    name: "Juliano Wachholz",
    email: "juliano.w@agroverde.coop.br",
    phone: "+5542991440076",
    jobTitle: "Diretor administrativo",
    companyId: "cmp_006",
    ownerId: "usr_bruno",
    stage: "oportunidade",
    score: 64,
    origin: "email",
    city: "Ponta Grossa",
    state: "PR",
    tags: ["tag_particular"],
    hue: 280,
    lastDays: 4,
    createdDays: 90,
  },
  {
    id: "cnt_013",
    name: "Priscilla Domingues",
    email: "priscilla.domingues@gmail.com",
    phone: "+5541994880023",
    ownerId: "usr_rafael",
    stage: "cliente",
    score: 55,
    origin: "whatsapp",
    city: "Pinhais",
    state: "PR",
    tags: ["tag_exame", "tag_convenio"],
    hue: 160,
    lastDays: 1,
    createdDays: 320,
  },
  {
    id: "cnt_014",
    name: "Arnaldo Petry",
    email: "arnaldo.petry@gmail.com",
    phone: "+5541996330011",
    ownerId: "usr_diego",
    stage: "inativo",
    score: 8,
    origin: "phone",
    city: "Curitiba",
    state: "PR",
    tags: [],
    hue: 218,
    lastDays: 300,
    createdDays: 800,
    duplicateOf: "cnt_001",
  },
]);

const bundle = buildConversations(ORG_ID, queues, [
  {
    id: "cnv_001",
    contactId: "cnt_001",
    channel: "whatsapp",
    channelAccountId: "chan_wa_atendimento",
    queueId: "queue_matriculas",
    state: "nova",
    subject: "Remarcar cardiologia de quinta",
    priority: "normal",
    tagIds: ["tag_convenio", "tag_idoso"],
    unreadCount: 1,
    openedMinutesAgo: 4,
    messages: [
      {
        from: "contato",
        authorLabel: "Neide Comparin",
        body: "Boa tarde. Não vou conseguir ir na quinta às 14h, meu filho não pode me levar. Tem outro dia?",
        minutesAgo: 4,
      },
      {
        from: "bot",
        authorLabel: "Assistente Vitalis",
        body: "Boa tarde, dona Neide! Tenho terça às 9h30 e quarta às 15h com o Dr. Aluísio, na unidade Batel. Alguma serve?",
        minutesAgo: 3,
        status: "entregue",
      },
    ],
    notes: [
      {
        authorId: "usr_marina",
        authorLabel: "Marina Duarte",
        body: "Paciente com prioridade legal. Se ela pedir encaixe pela manhã, pode abrir o horário das 8h.",
        minutesAgo: 2,
      },
    ],
  },
  {
    id: "cnv_002",
    contactId: "cnt_003",
    channel: "whatsapp",
    channelAccountId: "chan_wa_atendimento",
    queueId: "queue_fiscal",
    assigneeId: "usr_juliana",
    state: "aguardando_interno",
    subject: "Autorização de ressonância — Unimed",
    priority: "alta",
    tagIds: ["tag_convenio", "tag_exame"],
    unreadCount: 0,
    openedMinutesAgo: 2100,
    firstRespondedMinutesAgo: 2085,
    messages: [
      {
        from: "contato",
        authorLabel: "Andréa Locatelli",
        body: "O médico pediu ressonância de joelho. Preciso de autorização?",
        minutesAgo: 2100,
      },
      {
        from: "agente",
        authorId: "usr_juliana",
        authorLabel: "Silvana Ito",
        body: "Precisa sim. Já enviei a guia com o laudo do seu ortopedista para a Unimed. O prazo da operadora é de até 5 dias úteis.",
        minutesAgo: 2085,
        status: "lida",
      },
      {
        from: "agente",
        authorId: "usr_juliana",
        authorLabel: "Silvana Ito",
        body: "Estamos no terceiro dia. Assim que a senha sair, eu já deixo o horário reservado para você escolher.",
        minutesAgo: 180,
        status: "entregue",
      },
    ],
  },
  {
    id: "cnv_003",
    contactId: "cnt_005",
    channel: "instagram",
    channelAccountId: "chan_instagram",
    queueId: "queue_comercial",
    assigneeId: "usr_bruno",
    state: "em_atendimento",
    subject: "Check-up executivo — o que inclui?",
    priority: "normal",
    tagIds: ["tag_checkup", "tag_particular"],
    unreadCount: 0,
    openedMinutesAgo: 65,
    firstRespondedMinutesAgo: 58,
    messages: [
      {
        from: "contato",
        authorLabel: "Fabiana Ceccon",
        body: "Vi o post do check-up executivo. O que está incluso e quanto custa?",
        minutesAgo: 65,
      },
      {
        from: "agente",
        authorId: "usr_bruno",
        authorLabel: "Rodrigo Assaf",
        body: "Oi, Fabiana! São 14 exames laboratoriais, eletrocardiograma, avaliação clínica e devolutiva com o médico, tudo em uma manhã. R$ 1.290 particular, com 10% à vista.",
        minutesAgo: 58,
        status: "lida",
      },
      {
        from: "contato",
        authorLabel: "Fabiana Ceccon",
        body: "Dá para fazer num sábado?",
        minutesAgo: 40,
      },
      {
        from: "agente",
        authorId: "usr_bruno",
        authorLabel: "Rodrigo Assaf",
        body: "Dá sim, temos sábado de manhã na unidade Batel. Tenho 16/08 e 23/08 com vaga.",
        minutesAgo: 36,
        status: "entregue",
      },
    ],
  },
  {
    id: "cnv_004",
    contactId: "cnt_006",
    channel: "whatsapp",
    channelAccountId: "chan_wa_atendimento",
    queueId: "queue_matriculas",
    state: "em_triagem",
    subject: "Faltou à consulta de ontem",
    priority: "normal",
    tagIds: ["tag_falta", "tag_idoso"],
    unreadCount: 1,
    openedMinutesAgo: 40,
    handoffSummary:
      "Paciente faltou pela segunda vez em 60 dias. A política pede análise humana antes de reagendar — o assistente reuniu o histórico e parou aí.",
    botSessionId: "bot_sess_5510",
    messages: [
      {
        from: "contato",
        authorLabel: "Osvaldo Brandt",
        body: "Perdi a consulta de ontem, passei mal de manhã. Consigo remarcar?",
        minutesAgo: 40,
      },
      {
        from: "bot",
        authorLabel: "Assistente Vitalis",
        body: "Sinto muito, seu Osvaldo. Localizei a falta de ontem e uma anterior em junho. Como são duas, vou passar para a recepção avaliar o reagendamento com você.",
        minutesAgo: 39,
        status: "entregue",
      },
    ],
  },
  {
    id: "cnv_005",
    contactId: "cnt_008",
    channel: "whatsapp",
    channelAccountId: "chan_wa_comercial",
    queueId: "queue_regularizacao",
    assigneeId: "usr_diego",
    state: "aguardando_cliente",
    subject: "ASO de 12 motoristas — prazo de entrega",
    priority: "alta",
    tagIds: ["tag_exame"],
    unreadCount: 0,
    openedMinutesAgo: 900,
    firstRespondedMinutesAgo: 890,
    messages: [
      {
        from: "contato",
        authorLabel: "Márcio Bandeira",
        body: "Bom dia! Os ASOs dos 12 motoristas que passaram na segunda já saíram? A fiscalização é sexta.",
        minutesAgo: 900,
      },
      {
        from: "agente",
        authorId: "usr_diego",
        authorLabel: "Paulo Menegatti",
        body: "Bom dia, Márcio. Dez estão liberados e dois dependem de audiometria complementar, marcada para amanhã às 8h. Envio o lote completo quinta de manhã.",
        minutesAgo: 890,
        status: "lida",
      },
    ],
  },
  {
    id: "cnv_006",
    contactId: "cnt_009",
    channel: "whatsapp",
    channelAccountId: "chan_wa_atendimento",
    queueId: "queue_fiscal",
    assigneeId: "usr_juliana",
    state: "em_atendimento",
    subject: "Cobrança de consulta já paga",
    priority: "alta",
    tagIds: ["tag_inadimplente"],
    unreadCount: 0,
    openedMinutesAgo: 300,
    firstRespondedMinutesAgo: 290,
    messages: [
      {
        from: "contato",
        authorLabel: "Simone Grzybowski",
        body: "Recebi cobrança de uma consulta que paguei em dinheiro na recepção em julho. Tenho o recibo.",
        minutesAgo: 300,
      },
      {
        from: "agente",
        authorId: "usr_juliana",
        authorLabel: "Silvana Ito",
        body: "Vou verificar agora. Pode me mandar a foto do recibo com a data? Se estiver conciliado, eu cancelo a cobrança hoje mesmo.",
        minutesAgo: 290,
        status: "lida",
      },
      { from: "contato", authorLabel: "Simone Grzybowski", body: "Mandei aqui.", minutesAgo: 240 },
    ],
    notes: [
      {
        authorId: "usr_juliana",
        authorLabel: "Silvana Ito",
        body: "Recibo confere com o caixa do dia 18/07. Lançamento duplicado na integração do faturamento — terceira ocorrência do mês.",
        minutesAgo: 200,
        mentions: ["usr_alex"],
      },
    ],
  },
  {
    id: "cnv_007",
    contactId: "cnt_011",
    channel: "phone",
    channelAccountId: "chan_wa_atendimento",
    queueId: "queue_matriculas",
    assigneeId: "usr_marina",
    state: "resolvida",
    subject: "Retorno de endocrinologia agendado",
    priority: "normal",
    tagIds: ["tag_retorno", "tag_idoso"],
    unreadCount: 0,
    openedMinutesAgo: 4300,
    firstRespondedMinutesAgo: 4298,
    satisfactionScore: 5,
    messages: [
      {
        from: "contato",
        authorLabel: "Terezinha Alcântara",
        body: "Liguei para marcar o retorno com a Dra. Cristina.",
        minutesAgo: 4300,
      },
      {
        from: "agente",
        authorId: "usr_marina",
        authorLabel: "Marina Duarte",
        body: "Marquei para 19/08 às 10h, unidade Água Verde. Vou mandar a confirmação por WhatsApp também.",
        minutesAgo: 4298,
        status: "entregue",
      },
    ],
  },
  {
    id: "cnv_008",
    contactId: "cnt_010",
    channel: "webchat",
    channelAccountId: "chan_wa_atendimento",
    queueId: "queue_comercial",
    state: "nova",
    subject: "Dermatologia — primeira consulta particular",
    priority: "normal",
    tagIds: ["tag_primeira_consulta", "tag_particular"],
    unreadCount: 1,
    openedMinutesAgo: 9,
    messages: [
      {
        from: "contato",
        authorLabel: "Renan Piccoli",
        body: "Quanto custa a consulta de dermatologia particular e tem horário à noite?",
        minutesAgo: 9,
      },
      {
        from: "bot",
        authorLabel: "Assistente Vitalis",
        body: "Consulta dermatológica particular custa R$ 380. Temos agenda às terças e quintas até 20h na unidade Batel.",
        minutesAgo: 8,
        status: "entregue",
      },
    ],
  },
]);

const pipelines: Pipeline[] = [
  {
    id: "pipe_vendas",
    organizationId: ORG_ID,
    name: "Contratos corporativos",
    description: "Empresas que contratam exame ocupacional, check-up ou convênio coletivo.",
    stages: [
      {
        id: "stg_novo",
        name: "Contato inicial",
        order: 1,
        probability: 10,
        stalledAfterDays: 4,
        kind: "aberta",
      },
      {
        id: "stg_qualificacao",
        name: "Levantamento de escopo",
        order: 2,
        probability: 30,
        stalledAfterDays: 6,
        kind: "aberta",
      },
      {
        id: "stg_proposta",
        name: "Proposta enviada",
        order: 3,
        probability: 55,
        stalledAfterDays: 8,
        kind: "aberta",
      },
      {
        id: "stg_negociacao",
        name: "Ajuste contratual",
        order: 4,
        probability: 80,
        stalledAfterDays: 12,
        kind: "aberta",
      },
      {
        id: "stg_ganho",
        name: "Contrato assinado",
        order: 5,
        probability: 100,
        stalledAfterDays: 120,
        kind: "ganha",
      },
      {
        id: "stg_perdido",
        name: "Perdido",
        order: 6,
        probability: 0,
        stalledAfterDays: 120,
        kind: "perdida",
      },
    ],
    createdAt: offsetIso({ days: -500 }),
    updatedAt: offsetIso({ days: -18 }),
  },
  {
    id: "pipe_matriculas",
    organizationId: ORG_ID,
    name: "Check-up particular",
    description: "Interessados em pacote de check-up, do primeiro contato à realização.",
    stages: [
      {
        id: "stg_interesse",
        name: "Interesse",
        order: 1,
        probability: 15,
        stalledAfterDays: 2,
        kind: "aberta",
      },
      {
        id: "stg_inscricao",
        name: "Orçamento enviado",
        order: 2,
        probability: 40,
        stalledAfterDays: 3,
        kind: "aberta",
      },
      {
        id: "stg_pagamento",
        name: "Data reservada",
        order: 3,
        probability: 75,
        stalledAfterDays: 3,
        kind: "aberta",
      },
      {
        id: "stg_matriculado",
        name: "Check-up realizado",
        order: 4,
        probability: 100,
        stalledAfterDays: 45,
        kind: "ganha",
      },
      {
        id: "stg_desistiu",
        name: "Desistiu",
        order: 5,
        probability: 0,
        stalledAfterDays: 45,
        kind: "perdida",
      },
    ],
    createdAt: offsetIso({ days: -180 }),
    updatedAt: offsetIso({ days: -5 }),
  },
];

const deals = buildDeals(ORG_ID, [
  {
    id: "dl_001",
    title: "Colégio Santa Inês — saúde corporativa",
    pipelineId: "pipe_vendas",
    stageId: "stg_proposta",
    contactId: "cnt_007",
    companyId: "cmp_003",
    ownerId: "usr_bruno",
    amountCents: 3_840_000,
    probability: 55,
    expectedCloseDays: 14,
    product: "Check-up corporativo anual",
    stageEnteredDays: 3,
    createdDays: 40,
  },
  {
    id: "dl_002",
    title: "Metalúrgica Paraná Sul — ASO 2026",
    pipelineId: "pipe_vendas",
    stageId: "stg_ganho",
    contactId: "cnt_004",
    companyId: "cmp_002",
    ownerId: "usr_bruno",
    amountCents: 7_200_000,
    probability: 100,
    expectedCloseDays: -3,
    product: "Exame ocupacional (PCMSO)",
    stageEnteredDays: 3,
    createdDays: 70,
  },
  {
    id: "dl_003",
    title: "Transportes Iguaçu — renovação",
    pipelineId: "pipe_vendas",
    stageId: "stg_negociacao",
    contactId: "cnt_008",
    companyId: "cmp_004",
    ownerId: "usr_bruno",
    amountCents: 2_650_000,
    probability: 80,
    expectedCloseDays: 7,
    product: "ASO + audiometria",
    stageEnteredDays: 2,
    createdDays: 55,
  },
  {
    id: "dl_004",
    title: "Agro Verde — programa de saúde",
    pipelineId: "pipe_vendas",
    stageId: "stg_qualificacao",
    contactId: "cnt_012",
    companyId: "cmp_006",
    ownerId: "usr_bruno",
    amountCents: 5_100_000,
    probability: 30,
    expectedCloseDays: 30,
    product: "Convênio coletivo",
    stageEnteredDays: 4,
    createdDays: 90,
  },
  {
    id: "dl_005",
    title: "Unimed — credenciamento de nova unidade",
    pipelineId: "pipe_vendas",
    stageId: "stg_novo",
    contactId: "cnt_003",
    companyId: "cmp_001",
    ownerId: "usr_alex",
    amountCents: 12_000_000,
    probability: 10,
    expectedCloseDays: 60,
    product: "Credenciamento",
    stageEnteredDays: 1,
    createdDays: 12,
  },
  {
    id: "dl_006",
    title: "SulAmérica — reajuste de tabela",
    pipelineId: "pipe_vendas",
    stageId: "stg_perdido",
    contactId: "cnt_003",
    companyId: "cmp_005",
    ownerId: "usr_alex",
    amountCents: 4_500_000,
    probability: 0,
    expectedCloseDays: -20,
    product: "Renegociação de tabela",
    lostReason: "Operadora manteve a tabela anterior por mais 12 meses",
    stageEnteredDays: 20,
    createdDays: 120,
  },
  {
    id: "dl_007",
    title: "Check-up Fabiana Ceccon",
    pipelineId: "pipe_matriculas",
    stageId: "stg_pagamento",
    contactId: "cnt_005",
    ownerId: "usr_bruno",
    amountCents: 129_000,
    probability: 75,
    expectedCloseDays: 6,
    product: "Check-up executivo",
    stageEnteredDays: 0,
    createdDays: 4,
  },
  {
    id: "dl_008",
    title: "Check-up Wilson Nakata",
    pipelineId: "pipe_matriculas",
    stageId: "stg_matriculado",
    contactId: "cnt_004",
    ownerId: "usr_bruno",
    amountCents: 129_000,
    probability: 100,
    expectedCloseDays: -6,
    product: "Check-up executivo",
    stageEnteredDays: 6,
    createdDays: 30,
  },
  {
    id: "dl_009",
    title: "Check-up Juliano Wachholz",
    pipelineId: "pipe_matriculas",
    stageId: "stg_inscricao",
    contactId: "cnt_012",
    ownerId: "usr_bruno",
    amountCents: 258_000,
    probability: 40,
    expectedCloseDays: 10,
    product: "Check-up casal",
    stageEnteredDays: 2,
    createdDays: 8,
  },
  {
    id: "dl_010",
    title: "Check-up Renan Piccoli",
    pipelineId: "pipe_matriculas",
    stageId: "stg_interesse",
    contactId: "cnt_010",
    ownerId: "usr_rafael",
    amountCents: 38_000,
    probability: 15,
    expectedCloseDays: 5,
    product: "Consulta dermatológica",
    stageEnteredDays: 0,
    createdDays: 2,
  },
  {
    id: "dl_011",
    title: "Check-up Gustavo Perotto",
    pipelineId: "pipe_matriculas",
    stageId: "stg_desistiu",
    contactId: "cnt_002",
    ownerId: "usr_rafael",
    amountCents: 129_000,
    probability: 0,
    expectedCloseDays: -9,
    product: "Check-up executivo",
    lostReason: "Empresa passou a cobrir o exame pelo convênio",
    stageEnteredDays: 9,
    createdDays: 25,
  },
  {
    id: "dl_012",
    title: "Check-up Priscilla Domingues",
    pipelineId: "pipe_matriculas",
    stageId: "stg_pagamento",
    contactId: "cnt_013",
    ownerId: "usr_rafael",
    amountCents: 96_000,
    probability: 75,
    expectedCloseDays: 3,
    product: "Check-up básico",
    stageEnteredDays: 1,
    createdDays: 6,
  },
]);

const tasks = buildTasks(ORG_ID, [
  {
    id: "tsk_001",
    title: "Abrir encaixe de 8h para dona Neide",
    contactId: "cnt_001",
    dueHours: 2,
    assigneeId: "usr_marina",
    kind: "followup",
  },
  {
    id: "tsk_002",
    title: "Cobrar senha da ressonância na Unimed",
    contactId: "cnt_003",
    dueHours: 20,
    assigneeId: "usr_juliana",
    kind: "ligacao",
  },
  {
    id: "tsk_003",
    title: "Cancelar cobrança duplicada e responder paciente",
    contactId: "cnt_009",
    dueHours: 6,
    assigneeId: "usr_juliana",
    kind: "documento",
  },
  {
    id: "tsk_004",
    title: "Enviar lote de ASOs para Transportes Iguaçu",
    contactId: "cnt_008",
    dealId: "dl_003",
    dueHours: 30,
    assigneeId: "usr_diego",
    kind: "email",
  },
  {
    id: "tsk_005",
    title: "Reunião de escopo — Colégio Santa Inês",
    contactId: "cnt_007",
    dealId: "dl_001",
    dueHours: 48,
    assigneeId: "usr_bruno",
    kind: "reuniao",
  },
  {
    id: "tsk_006",
    title: "Revisar política de falta recorrente com a diretoria",
    contactId: "cnt_006",
    dueHours: 72,
    assigneeId: "usr_alex",
    kind: "followup",
  },
]);

const segments: Segment[] = [
  {
    id: "seg_confirmacao_48h",
    organizationId: ORG_ID,
    name: "Consultas nas próximas 48 horas",
    description: "Base da régua de confirmação. Recalculada a cada disparo.",
    match: "todas",
    dynamic: true,
    groups: [
      {
        id: "grp_1",
        match: "todas",
        rules: [
          {
            id: "r_1",
            field: "agenda.consulta_em",
            fieldLabel: "Consulta em (horas)",
            operator: "menor_que",
            value: "48",
          },
          {
            id: "r_2",
            field: "agenda.status",
            fieldLabel: "Status do agendamento",
            operator: "igual_a",
            value: "Agendado",
          },
        ],
      },
    ],
    estimatedSize: 312,
    eligibleSize: 298,
    exclusions: [
      { reason: "Sem consentimento de atendimento", count: 6 },
      { reason: "Já confirmou", count: 8 },
    ],
    lastCalculatedAt: offsetIso({ hours: -1 }),
    createdAt: offsetIso({ days: -200 }),
    updatedAt: offsetIso({ hours: -1 }),
  },
  {
    id: "seg_retorno_atrasado",
    organizationId: ORG_ID,
    name: "Retorno vencido há mais de 90 dias",
    description: "Pacientes crônicos sem consulta de acompanhamento no trimestre.",
    match: "todas",
    dynamic: true,
    groups: [
      {
        id: "grp_1",
        match: "todas",
        rules: [
          {
            id: "r_1",
            field: "contato.tag",
            fieldLabel: "Tag",
            operator: "igual_a",
            value: "Retorno",
          },
          {
            id: "r_2",
            field: "agenda.ultima_consulta",
            fieldLabel: "Última consulta (dias)",
            operator: "maior_que",
            value: "90",
          },
        ],
      },
    ],
    estimatedSize: 486,
    eligibleSize: 402,
    exclusions: [
      { reason: "Sem consentimento de marketing", count: 58 },
      { reason: "Limite de frequência (30 dias)", count: 26 },
    ],
    lastCalculatedAt: offsetIso({ hours: -14 }),
    createdAt: offsetIso({ days: -110 }),
    updatedAt: offsetIso({ hours: -14 }),
  },
];

const messageTemplates: MessageTemplate[] = [
  {
    id: "tpl_confirmacao",
    organizationId: ORG_ID,
    name: "confirmacao_consulta_v5",
    channel: "whatsapp",
    category: "utilidade",
    language: "pt_BR",
    status: "aprovado",
    body: "Olá, {{1}}! Sua consulta com {{2}} é {{3}}, na unidade {{4}}. Responda 1 para confirmar ou 2 para remarcar.",
    variables: [
      "contato.primeiro_nome",
      "consulta.profissional",
      "consulta.data",
      "consulta.unidade",
    ],
    buttons: ["Confirmar", "Remarcar"],
    quality: "alta",
    createdAt: offsetIso({ days: -300 }),
    updatedAt: offsetIso({ days: -25 }),
  },
  {
    id: "tpl_preparo",
    organizationId: ORG_ID,
    name: "preparo_exame_v2",
    channel: "whatsapp",
    category: "utilidade",
    language: "pt_BR",
    status: "aprovado",
    body: "{{1}}, seu exame {{2}} é amanhã às {{3}}. Preparo: {{4}}. Traga documento com foto e o pedido médico.",
    variables: ["contato.primeiro_nome", "exame.nome", "exame.hora", "exame.preparo"],
    quality: "alta",
    createdAt: offsetIso({ days: -240 }),
    updatedAt: offsetIso({ days: -40 }),
  },
  {
    id: "tpl_retorno",
    organizationId: ORG_ID,
    name: "retorno_acompanhamento_v1",
    channel: "whatsapp",
    category: "marketing",
    language: "pt_BR",
    status: "em_analise",
    body: "Olá, {{1}}! Faz {{2}} meses desde sua última consulta de acompanhamento. Quer que eu veja um horário?",
    variables: ["contato.primeiro_nome", "acompanhamento.meses"],
    createdAt: offsetIso({ days: -11 }),
    updatedAt: offsetIso({ days: -3 }),
  },
];

const campaigns = buildCampaigns(ORG_ID, [
  {
    id: "cmp_confirmacao_diaria",
    name: "Confirmação de consultas — 48 h",
    objective: "Reduzir falta confirmando consulta dois dias antes, com remarcação em um toque.",
    channel: "whatsapp",
    channelAccountId: "chan_wa_atendimento",
    segmentId: "seg_confirmacao_48h",
    templateId: "tpl_confirmacao",
    status: "concluida",
    ownerId: "usr_marina",
    startedHoursAgo: 8,
    finishedHoursAgo: 6,
    utm: { source: "whatsapp", medium: "crm", campaign: "confirmacao_48h" },
    metrics: {
      eligible: 298,
      excluded: 14,
      queued: 298,
      sent: 298,
      delivered: 291,
      read: 268,
      replied: 247,
      converted: 231,
      failed: 7,
      optOuts: 1,
      costCents: 14_900,
    },
    throttle: { batchSize: 100, intervalMinutes: 5, maxPerHour: 1200 },
    deliveryTimeline: [
      { label: "07h", value: 100 },
      { label: "08h", value: 100 },
      { label: "09h", value: 98 },
    ],
  },
  {
    id: "cmp_retorno_cronicos",
    name: "Retorno de acompanhamento — crônicos",
    objective: "Reagendar pacientes crônicos sem consulta há mais de 90 dias.",
    channel: "whatsapp",
    channelAccountId: "chan_wa_atendimento",
    segmentId: "seg_retorno_atrasado",
    templateId: "tpl_retorno",
    status: "agendada",
    ownerId: "usr_carla",
    scheduledInHours: 40,
    utm: { source: "whatsapp", medium: "crm", campaign: "retorno_cronicos" },
    metrics: {
      eligible: 402,
      excluded: 84,
      queued: 0,
      sent: 0,
      delivered: 0,
      read: 0,
      replied: 0,
      converted: 0,
      failed: 0,
      optOuts: 0,
      costCents: 0,
    },
  },
]);

const timeline = buildTimeline({
  orgId: ORG_ID,
  contacts,
  conversations: bundle.conversations,
  messages: bundle.messages,
  deals,
  pipelines,
  users,
  touches: [
    {
      contactId: "cnt_001",
      kind: "campanha",
      title: "Campanha recebida — Confirmação 48 h",
      description: "Entregue e respondida com 2 (remarcar).",
      hoursAgo: 7,
      channel: "whatsapp",
      domainEvent: "campaign.delivered",
    },
    {
      contactId: "cnt_011",
      kind: "campanha",
      title: "Campanha recebida — Confirmação 48 h",
      description: "Entregue e confirmada em 4 minutos.",
      hoursAgo: 7,
      channel: "whatsapp",
      domainEvent: "campaign.delivered",
    },
    {
      contactId: "cnt_006",
      kind: "automacao",
      title: "Automação executada — Falta registrada",
      description:
        'Regra "segunda falta em 60 dias" bloqueou reagendamento automático e abriu triagem humana.',
      hoursAgo: 1,
      domainEvent: "rule.executed",
    },
    {
      contactId: "cnt_009",
      kind: "automacao",
      title: "Automação executada — Cobrança contestada",
      description: "Conversa marcada como alta e financeiro notificado.",
      hoursAgo: 4,
      domainEvent: "rule.executed",
    },
    {
      contactId: "cnt_005",
      kind: "automacao",
      title: "Jornada iniciada — Check-up executivo",
      description: "Entrada por evento lead.qualified. Versão publicada v4.",
      hoursAgo: 12,
      domainEvent: "journey.enrolled",
    },
  ],
});

export const clinicaOverlay: DemoOverlay = {
  meta: CLINICA_META,
  organization,
  teams,
  users,
  queues,
  channelAccounts,
  tags,
  skills,
  closingReasons,
  customFields,
  cannedResponses,
  companies,
  contacts,
  conversations: bundle.conversations,
  messages: bundle.messages,
  internalNotes: bundle.internalNotes,
  timeline,
  pipelines,
  deals,
  tasks,
  segments,
  campaigns,
  messageTemplates,
};
