/**
 * Vertical de demonstração — e-commerce (Lumini Casa).
 *
 * O que esta base demonstra e a contabilidade não demonstra: **volume alto com
 * ticket baixo**. A conversa dura três mensagens, a pergunta é sempre uma de
 * cinco ("cadê meu pedido", "quero trocar", "cabe no meu vão", "tem frete
 * grátis", "chegou quebrado") e a diferença entre atender bem e mal é o tempo
 * até a primeira resposta, não a profundidade dela.
 *
 * É a base certa para mostrar o agente de IA resolvendo sozinho: rastreio e
 * política de troca são leitura, e leitura o agente executa. Reembolso é
 * escrita, e escrita espera clique de gente — a mesma disciplina que vale em
 * toda a plataforma.
 */

import type { DemoOverlay, DemoVerticalMeta } from "../types";
import type { Pipeline, Tag } from "../../types/crm";
import type { CannedResponse } from "../../types/inbox";
import type { MessageTemplate, Segment } from "../../types/marketing";
import type { Organization, Team } from "../../types/organization";
import { ORG_ID } from "../../mock/organization";
import { offsetIso } from "../../utils/datetime";
import {
  buildCampaigns,
  buildChannelAccounts,
  buildClosingReasons,
  buildCompanies,
  buildContacts,
  buildConversations,
  buildCustomFields,
  buildDeals,
  buildQueues,
  buildSkills,
  buildTasks,
  buildTimeline,
  buildUsers,
} from "../build";

const BRAND = "Lumini Casa";

export const ECOMMERCE_META: DemoVerticalMeta = {
  id: "ecommerce",
  name: "E-commerce",
  company: BRAND,
  tagline: "Loja de casa e decoração, D2C e atacado",
  description:
    "Volume alto e conversa curta: rastreio, troca, prazo de entrega e dúvida de produto. " +
    "É onde o agente de IA resolve sozinho a maior fatia — e onde a fronteira entre o que ele " +
    "executa e o que espera aprovação humana fica visível na tela.",
  hue: 174,
  highlights: [
    "Agente de IA resolve rastreio e política de troca sem passar por atendente.",
    "Reembolso é escrita: o agente propõe, uma pessoa confirma no Inbox.",
    "Recuperação de carrinho como funil, com valor esperado por etapa.",
  ],
  channels: ["whatsapp", "instagram", "webchat", "email"],
  stats: [
    { label: "Conversas / mês", value: "26 mil" },
    { label: "Primeira resposta", value: "40 s" },
    { label: "Resolução por IA", value: "61%" },
  ],
};

/* Organização ----------------------------------------------------------------- */

const organization: Organization = {
  id: ORG_ID,
  name: BRAND,
  slug: "lumini-casa",
  brandColor: "#134E4A",
  timezone: "America/Sao_Paulo",
};

const teams: Team[] = [
  { id: "team_atendimento", organizationId: ORG_ID, name: "Atendimento ao cliente" },
  { id: "team_comercial", organizationId: ORG_ID, name: "Vendas e atacado" },
  { id: "team_marketing", organizationId: ORG_ID, name: "Marketing e CRM" },
  { id: "team_aluno", organizationId: ORG_ID, name: "Pós-venda e logística" },
];

const skills = buildSkills(ORG_ID, [
  {
    key: "trocas",
    label: "Trocas e devoluções",
    description: "Política de troca, prazo de arrependimento e reembolso.",
    hue: 174,
  },
  {
    key: "logistica",
    label: "Logística",
    description: "Rastreio, extravio, reentrega e transportadora.",
    hue: 200,
  },
  {
    key: "produto",
    label: "Produto",
    description: "Medidas, materiais, montagem e compatibilidade.",
    hue: 45,
  },
  {
    key: "atacado",
    label: "Atacado",
    description: "Pedido mínimo, tabela de lojista e prazo de faturamento.",
    hue: 280,
  },
  {
    key: "retencao",
    label: "Retenção",
    description: "Reclamação pública, Procon e recuperação de cliente.",
    hue: 12,
  },
]);

const queues = buildQueues(ORG_ID, [
  {
    id: "queue_matriculas",
    name: "Pedidos e rastreio",
    description: "Onde está o pedido, prazo de entrega, reentrega e alteração de endereço.",
    channels: ["whatsapp", "webchat", "instagram", "email"],
    teamId: "team_aluno",
    firstResponseSlaMinutes: 5,
    resolutionSlaMinutes: 240,
    color: "200",
    scheduleId: "sched_estendido",
    distribution: {
      // O volume é a característica da fila: rodízio distribui, e a oferta curta
      // reflete que quem aceita em 30 s é quem consegue responder agora.
      model: "roleta",
      tiebreak: "roleta",
      delivery: "oferta",
      offerTimeoutSeconds: 30,
      maxOffers: 4,
      pauseOutsideSchedule: false,
    },
  },
  {
    id: "queue_fiscal",
    name: "Trocas e devoluções",
    description: "Arrependimento em 7 dias, produto avariado, reembolso e vale-compra.",
    channels: ["whatsapp", "email", "webchat"],
    teamId: "team_atendimento",
    firstResponseSlaMinutes: 15,
    resolutionSlaMinutes: 480,
    color: "174",
    distribution: {
      model: "habilidade",
      tiebreak: "menor_carga",
      delivery: "oferta",
      offerTimeoutSeconds: 60,
      maxOffers: 3,
      requiredSkills: ["trocas"],
    },
  },
  {
    id: "queue_comercial",
    name: "Atacado — lojistas",
    description: "Pedido mínimo, tabela de revenda, condição de pagamento e primeira compra.",
    channels: ["whatsapp", "email"],
    teamId: "team_comercial",
    firstResponseSlaMinutes: 10,
    resolutionSlaMinutes: 480,
    color: "280",
    scheduleId: "sched_comercial",
    distribution: {
      model: "proprietario",
      tiebreak: "roleta",
      delivery: "direta",
      requireAvailable: false,
    },
  },
  {
    id: "queue_regularizacao",
    name: "Reclamações e Procon",
    description: "Reclame Aqui, Procon e casos com prazo legal de resposta.",
    channels: ["email", "whatsapp"],
    teamId: "team_atendimento",
    firstResponseSlaMinutes: 30,
    resolutionSlaMinutes: 1440,
    color: "12",
    distribution: {
      // Manual de propósito: aqui o custo de responder rápido e errado é maior
      // que o de demorar dez minutos para escolher quem responde.
      model: "manual",
      overflowQueueId: "queue_fiscal",
    },
  },
]);

const channelAccounts = buildChannelAccounts(ORG_ID, [
  {
    id: "chan_wa_atendimento",
    kind: "whatsapp",
    label: "WhatsApp Loja",
    address: "+551140028922",
    queueId: "queue_matriculas",
    qualityRating: "alta",
    dailyLimit: 100000,
    sentToday: 18422,
  },
  {
    id: "chan_wa_comercial",
    kind: "whatsapp",
    label: "WhatsApp Atacado",
    address: "+551140028930",
    queueId: "queue_comercial",
    status: "degradado",
    qualityRating: "media",
    dailyLimit: 10000,
    sentToday: 3110,
  },
  {
    id: "chan_email_atendimento",
    kind: "email",
    label: "sac@luminicasa.com.br",
    address: "sac@luminicasa.com.br",
    queueId: "queue_fiscal",
  },
  {
    id: "chan_instagram",
    kind: "instagram",
    label: "@luminicasa",
    address: "luminicasa",
    queueId: "queue_matriculas",
  },
]);

const tags: Tag[] = [
  { id: "tag_pedido_atrasado", name: "Pedido atrasado", hue: 12 },
  { id: "tag_troca", name: "Troca", hue: 174 },
  { id: "tag_avariado", name: "Produto avariado", hue: 0 },
  { id: "tag_atacado", name: "Lojista", hue: 280 },
  { id: "tag_vip", name: "Cliente recorrente", hue: 45 },
  { id: "tag_carrinho", name: "Carrinho abandonado", hue: 200 },
  { id: "tag_primeira_compra", name: "Primeira compra", hue: 100 },
  { id: "tag_procon", name: "Procon", hue: 340 },
  { id: "tag_frete_gratis", name: "Frete grátis", hue: 160 },
  { id: "tag_urgente", name: "Urgente", hue: 30 },
];

const closingReasons = buildClosingReasons(ORG_ID, [
  {
    key: "rastreio_informado",
    label: "Rastreio informado",
    description: "Cliente recebeu o código e o prazo atualizado.",
    resolved: true,
  },
  {
    key: "troca_autorizada",
    label: "Troca autorizada",
    description: "Etiqueta de devolução emitida e enviada ao cliente.",
    resolved: true,
  },
  {
    key: "reembolso_efetuado",
    label: "Reembolso efetuado",
    description: "Estorno confirmado no meio de pagamento.",
    resolved: true,
    requiresNote: true,
  },
  {
    key: "duvida_produto",
    label: "Dúvida de produto respondida",
    description: "Medida, material ou compatibilidade esclarecida.",
    resolved: true,
  },
  {
    key: "sem_resposta",
    label: "Cliente não respondeu",
    description: "Três tentativas sem retorno em 48 horas.",
    resolved: false,
  },
  {
    key: "fora_politica",
    label: "Fora da política",
    description: "Pedido acima do prazo de arrependimento ou sem nota.",
    resolved: false,
    requiresNote: true,
  },
]);

const customFields = buildCustomFields(ORG_ID, [
  {
    key: "pedido_recente",
    label: "Último pedido",
    description: "Número do pedido mais recente do cliente.",
    entity: "contato",
    type: "texto",
  },
  {
    key: "ticket_medio",
    label: "Ticket médio",
    description: "Média dos pedidos pagos nos últimos 12 meses.",
    entity: "contato",
    type: "numero",
    derived: true,
  },
  {
    key: "canal_preferido",
    label: "Canal preferido",
    description: "Canal em que o cliente mais responde.",
    entity: "contato",
    type: "selecao",
    options: ["WhatsApp", "E-mail", "Instagram", "Webchat"],
  },
  {
    key: "cnpj_lojista",
    label: "CNPJ do lojista",
    description: "Documento do parceiro de atacado.",
    entity: "empresa",
    type: "documento",
    sensitive: true,
  },
]);

const cannedResponses: CannedResponse[] = [
  {
    id: "canned_rastreio",
    organizationId: ORG_ID,
    shortcut: "/rastreio",
    title: "Código de rastreio",
    body: "Seu pedido {{pedido.numero}} saiu para entrega e o código de rastreio é {{pedido.rastreio}}. A previsão é {{pedido.previsao}}.",
    channels: ["whatsapp", "webchat", "email"],
  },
  {
    id: "canned_troca",
    organizationId: ORG_ID,
    shortcut: "/troca",
    title: "Política de troca",
    body: "Você tem 7 dias corridos após o recebimento para desistir da compra, e 30 dias para trocar por defeito. Emito a etiqueta de devolução agora?",
    channels: ["whatsapp", "webchat", "email", "instagram"],
  },
  {
    id: "canned_avaria",
    organizationId: ORG_ID,
    shortcut: "/avaria",
    title: "Produto avariado",
    body: "Sinto muito pelo transtorno. Pode me enviar uma foto do produto e uma da embalagem? Com elas eu já abro a ocorrência com a transportadora.",
    channels: ["whatsapp", "webchat", "instagram"],
  },
  {
    id: "canned_medidas",
    organizationId: ORG_ID,
    shortcut: "/medidas",
    title: "Medidas do produto",
    body: "As medidas estão na aba Especificações da página do produto. Me diga o vão que você tem aí e eu confiro se encaixa.",
    channels: ["whatsapp", "webchat", "instagram"],
  },
  {
    id: "canned_atacado",
    organizationId: ORG_ID,
    shortcut: "/atacado",
    title: "Condição de atacado",
    body: "Para revenda o pedido mínimo é de R$ 1.500 na primeira compra, com tabela de lojista e faturamento em 30/60 dias mediante análise.",
    channels: ["whatsapp", "email"],
  },
];

/* Pessoas e empresas ------------------------------------------------------------ */

const users = buildUsers(ORG_ID, [
  {
    id: "usr_alex",
    name: "Otávio Barreto",
    email: "otavio.barreto@luminicasa.com.br",
    role: "admin_empresa",
    teamIds: ["team_atendimento", "team_comercial"],
    presence: "disponivel",
    capacity: 6,
    hue: 174,
    skills: ["trocas", "atacado"],
  },
  {
    id: "usr_marina",
    name: "Priscila Amorim",
    email: "priscila.amorim@luminicasa.com.br",
    role: "gestor_atendimento",
    teamIds: ["team_atendimento", "team_aluno"],
    presence: "disponivel",
    capacity: 5,
    hue: 30,
    skills: ["trocas", "logistica", "retencao"],
  },
  {
    id: "usr_rafael",
    name: "Caio Sampaio",
    email: "caio.sampaio@luminicasa.com.br",
    role: "atendente",
    teamIds: ["team_aluno"],
    presence: "disponivel",
    capacity: 12,
    hue: 200,
    skills: ["logistica"],
    scheduleId: "sched_estendido",
  },
  {
    id: "usr_juliana",
    name: "Nina Okamoto",
    email: "nina.okamoto@luminicasa.com.br",
    role: "atendente",
    teamIds: ["team_atendimento"],
    presence: "ocupado",
    capacity: 10,
    hue: 280,
    skills: ["trocas", "produto"],
    acceptingNew: false,
  },
  {
    id: "usr_bruno",
    name: "Wesley Prado",
    email: "wesley.prado@luminicasa.com.br",
    role: "gestor_comercial",
    teamIds: ["team_comercial"],
    presence: "disponivel",
    capacity: 6,
    hue: 45,
    skills: ["atacado"],
  },
  {
    id: "usr_carla",
    name: "Bianca Serra",
    email: "bianca.serra@luminicasa.com.br",
    role: "marketing",
    teamIds: ["team_marketing"],
    presence: "ausente",
    capacity: 3,
    hue: 340,
    skills: [],
  },
  {
    id: "usr_diego",
    name: "Igor Lacerda",
    email: "igor.lacerda@luminicasa.com.br",
    role: "atendente",
    teamIds: ["team_aluno"],
    presence: "offline",
    capacity: 12,
    hue: 100,
    skills: ["logistica", "produto"],
    scheduleId: "sched_estendido",
  },
]);

const companies = buildCompanies(ORG_ID, [
  {
    id: "cmp_001",
    name: "Casa & Cia Utilidades",
    document: "21.334.556/0001-70",
    segment: "Varejo — lojista",
    city: "Ribeirão Preto",
    state: "SP",
    contactsCount: 2,
    createdDays: 380,
    updatedDays: 4,
  },
  {
    id: "cmp_002",
    name: "Decorar Norte Distribuidora",
    document: "08.912.443/0001-21",
    segment: "Atacado",
    city: "Belém",
    state: "PA",
    contactsCount: 3,
    createdDays: 260,
    updatedDays: 1,
  },
  {
    id: "cmp_003",
    name: "Arquitetura Trilho Sul",
    document: "55.221.887/0001-04",
    segment: "Arquitetura e interiores",
    city: "Florianópolis",
    state: "SC",
    contactsCount: 2,
    createdDays: 190,
    updatedDays: 9,
  },
  {
    id: "cmp_004",
    name: "Hotelaria Vista Mar",
    document: "77.010.223/0001-66",
    segment: "Hotelaria",
    city: "Natal",
    state: "RN",
    contactsCount: 1,
    createdDays: 140,
    updatedDays: 21,
  },
  {
    id: "cmp_005",
    name: "Enxovais Bela Ponte",
    document: "31.887.220/0001-49",
    segment: "Varejo — lojista",
    city: "Juiz de Fora",
    state: "MG",
    contactsCount: 2,
    createdDays: 95,
    updatedDays: 2,
  },
  {
    id: "cmp_006",
    name: "Marketplace Vitrine BR",
    document: "12.556.998/0001-88",
    segment: "Marketplace",
    city: "São Paulo",
    state: "SP",
    contactsCount: 1,
    createdDays: 60,
    updatedDays: 6,
  },
]);

const contacts = buildContacts(ORG_ID, BRAND, [
  {
    id: "cnt_001",
    name: "Aline Castilho",
    email: "aline.castilho@gmail.com",
    phone: "+5511987450012",
    ownerId: "usr_marina",
    stage: "cliente",
    score: 78,
    origin: "whatsapp",
    city: "São Paulo",
    state: "SP",
    tags: ["tag_vip", "tag_pedido_atrasado"],
    hue: 30,
    lastDays: 0,
    createdDays: 420,
    fields: [
      { key: "pedido_recente", label: "Último pedido", value: "#248-9910" },
      { key: "ticket_medio", label: "Ticket médio", value: "R$ 612", derived: true },
    ],
  },
  {
    id: "cnt_002",
    name: "Fernando Guimarães",
    email: "fernando.guima@outlook.com",
    phone: "+5521996330087",
    ownerId: "usr_rafael",
    stage: "cliente",
    score: 54,
    origin: "webchat",
    city: "Rio de Janeiro",
    state: "RJ",
    tags: ["tag_troca"],
    hue: 200,
    lastDays: 0,
    createdDays: 95,
    fields: [{ key: "pedido_recente", label: "Último pedido", value: "#248-8874" }],
  },
  {
    id: "cnt_003",
    name: "Talita Moraes",
    email: "talita.moraes@gmail.com",
    phone: "+5531988220145",
    ownerId: "usr_juliana",
    stage: "cliente",
    score: 66,
    origin: "instagram",
    campaign: "Instagram — coleção verão",
    city: "Belo Horizonte",
    state: "MG",
    tags: ["tag_avariado", "tag_urgente"],
    hue: 340,
    lastDays: 0,
    createdDays: 40,
  },
  {
    id: "cnt_004",
    name: "Douglas Ferrari",
    email: "douglas@casaeciautilidades.com.br",
    phone: "+5516993410077",
    jobTitle: "Comprador",
    companyId: "cmp_001",
    ownerId: "usr_bruno",
    stage: "cliente",
    score: 88,
    origin: "email",
    city: "Ribeirão Preto",
    state: "SP",
    tags: ["tag_atacado", "tag_vip"],
    hue: 280,
    lastDays: 1,
    createdDays: 380,
  },
  {
    id: "cnt_005",
    name: "Rejane Bastos",
    email: "rejane@decorarnorte.com.br",
    phone: "+5591984120033",
    jobTitle: "Sócia",
    companyId: "cmp_002",
    ownerId: "usr_bruno",
    stage: "oportunidade",
    score: 71,
    origin: "whatsapp",
    city: "Belém",
    state: "PA",
    tags: ["tag_atacado"],
    hue: 174,
    lastDays: 1,
    createdDays: 26,
  },
  {
    id: "cnt_006",
    name: "Henrique Salles",
    email: "henrique.salles@gmail.com",
    phone: "+5541995870021",
    ownerId: "usr_diego",
    stage: "cliente",
    score: 41,
    origin: "whatsapp",
    city: "Curitiba",
    state: "PR",
    tags: ["tag_pedido_atrasado"],
    hue: 45,
    lastDays: 1,
    createdDays: 210,
  },
  {
    id: "cnt_007",
    name: "Marcela Pontes",
    email: "marcela.pontes@gmail.com",
    phone: "+5581987660019",
    ownerId: "usr_marina",
    stage: "lead_qualificado",
    score: 63,
    origin: "webchat",
    campaign: "Google Ads — cortina blackout",
    city: "Recife",
    state: "PE",
    tags: ["tag_carrinho"],
    hue: 100,
    lastDays: 0,
    createdDays: 3,
  },
  {
    id: "cnt_008",
    name: "Ricardo Tavolaro",
    email: "ricardo@trilhosul.arq.br",
    phone: "+5548991200064",
    jobTitle: "Arquiteto",
    companyId: "cmp_003",
    ownerId: "usr_bruno",
    stage: "oportunidade",
    score: 74,
    origin: "form",
    campaign: "Programa Arquitetos",
    city: "Florianópolis",
    state: "SC",
    tags: ["tag_atacado", "tag_primeira_compra"],
    hue: 218,
    lastDays: 2,
    createdDays: 34,
  },
  {
    id: "cnt_009",
    name: "Sabrina Duque",
    email: "sabrina.duque@gmail.com",
    phone: "+5511994520188",
    ownerId: "usr_juliana",
    stage: "cliente",
    score: 59,
    origin: "instagram",
    city: "Guarulhos",
    state: "SP",
    tags: ["tag_troca", "tag_frete_gratis"],
    hue: 12,
    lastDays: 2,
    createdDays: 130,
  },
  {
    id: "cnt_010",
    name: "Paulo Ambrósio",
    email: "paulo.ambrosio@vistamar.com.br",
    phone: "+5584988110052",
    jobTitle: "Gerente de compras",
    companyId: "cmp_004",
    ownerId: "usr_bruno",
    stage: "lead_qualificado",
    score: 57,
    origin: "email",
    city: "Natal",
    state: "RN",
    tags: ["tag_atacado"],
    hue: 160,
    lastDays: 5,
    createdDays: 48,
  },
  {
    id: "cnt_011",
    name: "Letícia Marques",
    email: "leticia.marques@gmail.com",
    phone: "+5551993330091",
    ownerId: "usr_marina",
    stage: "cliente",
    score: 82,
    origin: "whatsapp",
    city: "Porto Alegre",
    state: "RS",
    tags: ["tag_vip", "tag_procon"],
    hue: 0,
    lastDays: 0,
    createdDays: 640,
  },
  {
    id: "cnt_012",
    name: "Wagner Kubitschek",
    email: "wagner.k@belaponte.com.br",
    phone: "+5532991440076",
    jobTitle: "Proprietário",
    companyId: "cmp_005",
    ownerId: "usr_bruno",
    stage: "cliente",
    score: 69,
    origin: "whatsapp",
    city: "Juiz de Fora",
    state: "MG",
    tags: ["tag_atacado"],
    hue: 280,
    lastDays: 2,
    createdDays: 95,
  },
  {
    id: "cnt_013",
    name: "Camila Rezende",
    email: "camila.rezende@gmail.com",
    phone: "+5562994880023",
    ownerId: "usr_rafael",
    stage: "lead",
    score: 28,
    origin: "instagram",
    campaign: "Instagram — coleção verão",
    city: "Goiânia",
    state: "GO",
    tags: ["tag_carrinho"],
    hue: 45,
    lastDays: 4,
    createdDays: 6,
  },
  {
    id: "cnt_014",
    name: "Josué Bittencourt",
    email: "josue.bitt@gmail.com",
    phone: "+5511987450012",
    ownerId: "usr_diego",
    stage: "inativo",
    score: 9,
    origin: "webchat",
    city: "São Paulo",
    state: "SP",
    tags: [],
    hue: 218,
    lastDays: 240,
    createdDays: 500,
    duplicateOf: "cnt_001",
  },
]);

/* Conversas ---------------------------------------------------------------------- */

const bundle = buildConversations(ORG_ID, queues, [
  {
    id: "cnv_001",
    contactId: "cnt_001",
    channel: "whatsapp",
    channelAccountId: "chan_wa_atendimento",
    queueId: "queue_matriculas",
    state: "nova",
    subject: "Pedido #248-9910 parado há 4 dias",
    priority: "alta",
    tagIds: ["tag_pedido_atrasado", "tag_vip"],
    unreadCount: 2,
    openedMinutesAgo: 7,
    messages: [
      {
        from: "contato",
        authorLabel: "Aline Castilho",
        body: "Oi! Meu pedido 248-9910 está com o rastreio parado em Cajamar desde sexta. Vocês conseguem ver o que houve?",
        minutesAgo: 7,
      },
      {
        from: "bot",
        authorLabel: "Agente Lumini",
        body: "Oi, Aline! Localizei o pedido 248-9910. O objeto está retido na unidade de Cajamar desde 05/08 e a transportadora já registrou reentrega para amanhã.",
        minutesAgo: 6,
        status: "entregue",
      },
      {
        from: "contato",
        authorLabel: "Aline Castilho",
        body: "Amanhã não tem ninguém em casa. Consigo mudar para o endereço do trabalho?",
        minutesAgo: 5,
      },
    ],
    notes: [
      {
        authorId: "usr_marina",
        authorLabel: "Priscila Amorim",
        body: "Cliente recorrente, 11 pedidos no ano. Se a transportadora não aceitar a troca de endereço, autorizo reenvio por nossa conta.",
        minutesAgo: 4,
        mentions: ["usr_rafael"],
      },
    ],
  },
  {
    id: "cnv_002",
    contactId: "cnt_003",
    channel: "instagram",
    channelAccountId: "chan_instagram",
    queueId: "queue_fiscal",
    assigneeId: "usr_juliana",
    state: "em_atendimento",
    subject: "Luminária chegou com a cúpula trincada",
    priority: "urgente",
    tagIds: ["tag_avariado", "tag_urgente"],
    unreadCount: 0,
    openedMinutesAgo: 95,
    firstRespondedMinutesAgo: 88,
    messages: [
      {
        from: "contato",
        authorLabel: "Talita Moraes",
        body: "Gente, a luminária Pendente Ravena chegou hoje com a cúpula trincada. Foi presente de casamento, preciso resolver rápido.",
        minutesAgo: 95,
      },
      {
        from: "agente",
        authorId: "usr_juliana",
        authorLabel: "Nina Okamoto",
        body: "Que chato, Talita, sinto muito. Já vou abrir a ocorrência. Consegue me mandar uma foto da peça e uma da caixa por fora?",
        minutesAgo: 88,
        status: "lida",
      },
      {
        from: "contato",
        authorLabel: "Talita Moraes",
        body: "Acabei de mandar as duas no direct.",
        minutesAgo: 71,
      },
      {
        from: "agente",
        authorId: "usr_juliana",
        authorLabel: "Nina Okamoto",
        body: "Recebi. A caixa está amassada no canto, então é avaria de transporte e a reposição sai sem custo. Já separei uma nova para envio expresso hoje.",
        minutesAgo: 66,
        status: "lida",
      },
    ],
  },
  {
    id: "cnv_003",
    contactId: "cnt_002",
    channel: "webchat",
    channelAccountId: "chan_wa_atendimento",
    queueId: "queue_fiscal",
    state: "em_triagem",
    subject: "Troca de tamanho — tapete 200x250",
    priority: "normal",
    tagIds: ["tag_troca"],
    unreadCount: 1,
    openedMinutesAgo: 22,
    handoffSummary:
      "Cliente quer trocar o tapete 200x250 por 250x300. Dentro do prazo de 7 dias, produto sem uso. O agente calculou a diferença (R$ 340) e parou antes de gerar a cobrança — escrita exige confirmação humana.",
    botSessionId: "bot_sess_2291",
    messages: [
      {
        from: "contato",
        authorLabel: "Fernando Guimarães",
        body: "Comprei o tapete 200x250 mas ficou pequeno para a sala. Dá para trocar pelo 250x300?",
        minutesAgo: 22,
      },
      {
        from: "bot",
        authorLabel: "Agente Lumini",
        body: "Dá sim, Fernando. Seu pedido #248-8874 foi entregue há 3 dias, dentro dos 7 dias de arrependimento. A diferença entre os dois tamanhos é de R$ 340.",
        minutesAgo: 21,
        status: "entregue",
      },
      {
        from: "contato",
        authorLabel: "Fernando Guimarães",
        body: "Fechado, pode gerar.",
        minutesAgo: 20,
      },
      {
        from: "bot",
        authorLabel: "Agente Lumini",
        body: "Vou encaminhar para uma pessoa do time emitir a cobrança da diferença e a etiqueta de devolução — geração de cobrança precisa de confirmação humana aqui.",
        minutesAgo: 19,
        status: "entregue",
      },
    ],
  },
  {
    id: "cnv_004",
    contactId: "cnt_005",
    channel: "whatsapp",
    channelAccountId: "chan_wa_comercial",
    queueId: "queue_comercial",
    assigneeId: "usr_bruno",
    state: "aguardando_cliente",
    subject: "Primeira compra de atacado — Decorar Norte",
    priority: "alta",
    tagIds: ["tag_atacado"],
    unreadCount: 0,
    openedMinutesAgo: 620,
    firstRespondedMinutesAgo: 605,
    messages: [
      {
        from: "contato",
        authorLabel: "Rejane Bastos",
        body: "Boa tarde! Somos distribuidores em Belém e queremos trabalhar com a linha de cestos e mantas. Como funciona?",
        minutesAgo: 620,
      },
      {
        from: "agente",
        authorId: "usr_bruno",
        authorLabel: "Wesley Prado",
        body: "Boa tarde, Rejane! Pedido mínimo de R$ 1.500 na primeira compra, tabela de lojista com 42% de desconto e faturamento em 30/60 após análise de crédito.",
        minutesAgo: 605,
        status: "lida",
      },
      {
        from: "agente",
        authorId: "usr_bruno",
        authorLabel: "Wesley Prado",
        body: "Enviei a tabela e a ficha cadastral no seu e-mail. Assim que voltar, já separo o primeiro pedido.",
        minutesAgo: 604,
        status: "lida",
      },
    ],
    notes: [
      {
        authorId: "usr_bruno",
        authorLabel: "Wesley Prado",
        body: "Região sem representante hoje. Se fechar, vale avaliar exclusividade por 6 meses no Pará.",
        minutesAgo: 600,
      },
    ],
  },
  {
    id: "cnv_005",
    contactId: "cnt_011",
    channel: "email",
    channelAccountId: "chan_email_atendimento",
    queueId: "queue_regularizacao",
    assigneeId: "usr_marina",
    state: "em_atendimento",
    subject: "Notificação Procon — pedido #247-1180",
    priority: "urgente",
    tagIds: ["tag_procon", "tag_urgente"],
    unreadCount: 0,
    openedMinutesAgo: 1500,
    firstRespondedMinutesAgo: 1440,
    messages: [
      {
        from: "contato",
        authorLabel: "Letícia Marques",
        body: "Abri reclamação no Procon porque o reembolso do pedido #247-1180 não caiu em 30 dias, como prometido em 09/07.",
        minutesAgo: 1500,
      },
      {
        from: "agente",
        authorId: "usr_marina",
        authorLabel: "Priscila Amorim",
        body: "Letícia, verifiquei: o estorno foi solicitado ao adquirente em 12/07 e travou por divergência de CPF do titular. Reprocessei hoje com a correção e o prazo do emissor é de até 2 faturas.",
        minutesAgo: 1440,
        status: "lida",
      },
      {
        from: "agente",
        authorId: "usr_marina",
        authorLabel: "Priscila Amorim",
        body: "Como o atraso foi nosso, creditei R$ 120 em vale-compra sem prazo de validade. Vou responder o Procon com o comprovante ainda hoje.",
        minutesAgo: 1438,
        status: "entregue",
      },
    ],
    notes: [
      {
        authorId: "usr_marina",
        authorLabel: "Priscila Amorim",
        body: "Terceiro caso de divergência de CPF no estorno neste mês. Abri chamado com o adquirente — o padrão é sempre pedido pago em cartão de terceiro.",
        minutesAgo: 1400,
        mentions: ["usr_alex"],
      },
    ],
  },
  {
    id: "cnv_006",
    contactId: "cnt_007",
    channel: "webchat",
    channelAccountId: "chan_wa_atendimento",
    queueId: "queue_matriculas",
    state: "nova",
    subject: "Cortina blackout cabe em vão de 2,40 m?",
    priority: "normal",
    tagIds: ["tag_carrinho"],
    unreadCount: 1,
    openedMinutesAgo: 3,
    messages: [
      {
        from: "contato",
        authorLabel: "Marcela Pontes",
        body: "Boa tarde. A cortina blackout 2,60 m cobre um vão de 2,40 m com folga? Não quero ficar com sobra no chão.",
        minutesAgo: 3,
      },
      {
        from: "bot",
        authorLabel: "Agente Lumini",
        body: "Boa tarde, Marcela! Para vão de 2,40 m a recomendação é a de 2,60 m mesmo: sobram 10 cm de cada lado, que é o que impede a entrada de luz nas bordas.",
        minutesAgo: 2,
        status: "entregue",
      },
    ],
  },
  {
    id: "cnv_007",
    contactId: "cnt_006",
    channel: "whatsapp",
    channelAccountId: "chan_wa_atendimento",
    queueId: "queue_matriculas",
    assigneeId: "usr_rafael",
    state: "resolvida",
    subject: "Reentrega agendada — pedido #248-7710",
    priority: "normal",
    tagIds: ["tag_pedido_atrasado"],
    unreadCount: 0,
    openedMinutesAgo: 2880,
    firstRespondedMinutesAgo: 2875,
    satisfactionScore: 5,
    messages: [
      {
        from: "contato",
        authorLabel: "Henrique Salles",
        body: "A transportadora tentou entregar e eu não estava. Como faço?",
        minutesAgo: 2880,
      },
      {
        from: "agente",
        authorId: "usr_rafael",
        authorLabel: "Caio Sampaio",
        body: "Agendei a reentrega para quinta, entre 8h e 12h. Se preferir, também consigo redirecionar para uma agência próxima.",
        minutesAgo: 2875,
        status: "lida",
      },
      {
        from: "contato",
        authorLabel: "Henrique Salles",
        body: "Quinta está ótimo, obrigado!",
        minutesAgo: 2870,
      },
    ],
  },
  {
    id: "cnv_008",
    contactId: "cnt_009",
    channel: "whatsapp",
    channelAccountId: "chan_wa_atendimento",
    queueId: "queue_fiscal",
    assigneeId: "usr_juliana",
    state: "aguardando_interno",
    subject: "Estorno não identificado na fatura",
    priority: "alta",
    tagIds: ["tag_troca"],
    unreadCount: 0,
    openedMinutesAgo: 430,
    firstRespondedMinutesAgo: 420,
    messages: [
      {
        from: "contato",
        authorLabel: "Sabrina Duque",
        body: "Devolvi a manta no dia 22 e até agora não vi o estorno na fatura.",
        minutesAgo: 430,
      },
      {
        from: "agente",
        authorId: "usr_juliana",
        authorLabel: "Nina Okamoto",
        body: "A devolução foi recebida no CD em 25/07 e o estorno foi lançado em 28/07. Vou pedir ao financeiro o comprovante com o código de autorização para você levar ao banco.",
        minutesAgo: 420,
        status: "lida",
      },
    ],
    notes: [
      {
        authorId: "usr_juliana",
        authorLabel: "Nina Okamoto",
        body: "Financeiro respondeu que o comprovante sai só amanhã de manhã. Avisei a cliente do prazo.",
        minutesAgo: 200,
      },
    ],
  },
]);

/* Funis --------------------------------------------------------------------------- */

const pipelines: Pipeline[] = [
  {
    id: "pipe_vendas",
    organizationId: ORG_ID,
    name: "Atacado — lojistas",
    description: "Prospecção e primeira compra de revendedores, arquitetos e hotelaria.",
    stages: [
      {
        id: "stg_novo",
        name: "Cadastro recebido",
        order: 1,
        probability: 10,
        stalledAfterDays: 3,
        kind: "aberta",
      },
      {
        id: "stg_qualificacao",
        name: "Análise de crédito",
        order: 2,
        probability: 30,
        stalledAfterDays: 4,
        kind: "aberta",
      },
      {
        id: "stg_proposta",
        name: "Tabela enviada",
        order: 3,
        probability: 55,
        stalledAfterDays: 6,
        kind: "aberta",
      },
      {
        id: "stg_negociacao",
        name: "Montando o primeiro pedido",
        order: 4,
        probability: 80,
        stalledAfterDays: 8,
        kind: "aberta",
      },
      {
        id: "stg_ganho",
        name: "Pedido faturado",
        order: 5,
        probability: 100,
        stalledAfterDays: 90,
        kind: "ganha",
      },
      {
        id: "stg_perdido",
        name: "Perdido",
        order: 6,
        probability: 0,
        stalledAfterDays: 90,
        kind: "perdida",
      },
    ],
    createdAt: offsetIso({ days: -400 }),
    updatedAt: offsetIso({ days: -14 }),
  },
  {
    id: "pipe_matriculas",
    organizationId: ORG_ID,
    name: "Recuperação de carrinho",
    description: "Carrinhos acima de R$ 400 abandonados nas últimas 72 horas.",
    stages: [
      {
        id: "stg_interesse",
        name: "Carrinho abandonado",
        order: 1,
        probability: 12,
        stalledAfterDays: 1,
        kind: "aberta",
      },
      {
        id: "stg_inscricao",
        name: "Mensagem entregue",
        order: 2,
        probability: 30,
        stalledAfterDays: 1,
        kind: "aberta",
      },
      {
        id: "stg_pagamento",
        name: "Voltou ao checkout",
        order: 3,
        probability: 65,
        stalledAfterDays: 1,
        kind: "aberta",
      },
      {
        id: "stg_matriculado",
        name: "Compra concluída",
        order: 4,
        probability: 100,
        stalledAfterDays: 30,
        kind: "ganha",
      },
      {
        id: "stg_desistiu",
        name: "Desistiu",
        order: 5,
        probability: 0,
        stalledAfterDays: 30,
        kind: "perdida",
      },
    ],
    createdAt: offsetIso({ days: -160 }),
    updatedAt: offsetIso({ days: -3 }),
  },
];

const deals = buildDeals(ORG_ID, [
  {
    id: "dl_001",
    title: "Decorar Norte — primeira carga",
    pipelineId: "pipe_vendas",
    stageId: "stg_negociacao",
    contactId: "cnt_005",
    companyId: "cmp_002",
    ownerId: "usr_bruno",
    amountCents: 4_280_000,
    probability: 80,
    expectedCloseDays: 6,
    product: "Linha cestos e mantas",
    stageEnteredDays: 2,
    createdDays: 26,
    tagIds: ["tag_atacado"],
  },
  {
    id: "dl_002",
    title: "Casa & Cia — reposição trimestral",
    pipelineId: "pipe_vendas",
    stageId: "stg_ganho",
    contactId: "cnt_004",
    companyId: "cmp_001",
    ownerId: "usr_bruno",
    amountCents: 6_150_000,
    probability: 100,
    expectedCloseDays: -1,
    product: "Mix completo",
    stageEnteredDays: 1,
    createdDays: 40,
    tagIds: ["tag_atacado", "tag_vip"],
  },
  {
    id: "dl_003",
    title: "Trilho Sul — projeto residencial Jurerê",
    pipelineId: "pipe_vendas",
    stageId: "stg_proposta",
    contactId: "cnt_008",
    companyId: "cmp_003",
    ownerId: "usr_bruno",
    amountCents: 2_940_000,
    probability: 55,
    expectedCloseDays: 12,
    product: "Iluminação sob medida",
    stageEnteredDays: 3,
    createdDays: 34,
  },
  {
    id: "dl_004",
    title: "Vista Mar — enxoval 40 apartamentos",
    pipelineId: "pipe_vendas",
    stageId: "stg_qualificacao",
    contactId: "cnt_010",
    companyId: "cmp_004",
    ownerId: "usr_bruno",
    amountCents: 9_800_000,
    probability: 30,
    expectedCloseDays: 25,
    product: "Enxoval hoteleiro",
    stageEnteredDays: 5,
    createdDays: 48,
  },
  {
    id: "dl_005",
    title: "Bela Ponte — recompra de agosto",
    pipelineId: "pipe_vendas",
    stageId: "stg_negociacao",
    contactId: "cnt_012",
    companyId: "cmp_005",
    ownerId: "usr_bruno",
    amountCents: 1_870_000,
    probability: 80,
    expectedCloseDays: 4,
    product: "Linha enxoval",
    stageEnteredDays: 2,
    createdDays: 30,
    tagIds: ["tag_atacado"],
  },
  {
    id: "dl_006",
    title: "Vitrine BR — teste de marketplace",
    pipelineId: "pipe_vendas",
    stageId: "stg_perdido",
    contactId: "cnt_004",
    companyId: "cmp_006",
    ownerId: "usr_bruno",
    amountCents: 3_200_000,
    probability: 0,
    expectedCloseDays: -8,
    product: "Consignação",
    lostReason: "Comissão do marketplace inviabiliza a margem da linha",
    stageEnteredDays: 8,
    createdDays: 60,
  },
  {
    id: "dl_007",
    title: "Carrinho Marcela — cortinas e trilhos",
    pipelineId: "pipe_matriculas",
    stageId: "stg_pagamento",
    contactId: "cnt_007",
    ownerId: "usr_marina",
    amountCents: 84_000,
    probability: 65,
    expectedCloseDays: 1,
    product: "Cortina blackout 2,60 m",
    stageEnteredDays: 0,
    createdDays: 3,
    tagIds: ["tag_carrinho"],
  },
  {
    id: "dl_008",
    title: "Carrinho Camila — kit banheiro",
    pipelineId: "pipe_matriculas",
    stageId: "stg_inscricao",
    contactId: "cnt_013",
    ownerId: "usr_carla",
    amountCents: 47_000,
    probability: 30,
    expectedCloseDays: 2,
    product: "Kit banheiro Ravena",
    stageEnteredDays: 1,
    createdDays: 6,
    tagIds: ["tag_carrinho"],
  },
  {
    id: "dl_009",
    title: "Carrinho Sabrina — tapete sala",
    pipelineId: "pipe_matriculas",
    stageId: "stg_matriculado",
    contactId: "cnt_009",
    ownerId: "usr_carla",
    amountCents: 121_000,
    probability: 100,
    expectedCloseDays: -2,
    product: "Tapete 250x300",
    stageEnteredDays: 2,
    createdDays: 9,
  },
  {
    id: "dl_010",
    title: "Carrinho Henrique — luminárias",
    pipelineId: "pipe_matriculas",
    stageId: "stg_desistiu",
    contactId: "cnt_006",
    ownerId: "usr_carla",
    amountCents: 66_000,
    probability: 0,
    expectedCloseDays: -5,
    product: "Pendente Ravena",
    lostReason: "Comprou em concorrente com frete grátis",
    stageEnteredDays: 5,
    createdDays: 12,
  },
  {
    id: "dl_011",
    title: "Carrinho Aline — mesa lateral",
    pipelineId: "pipe_matriculas",
    stageId: "stg_interesse",
    contactId: "cnt_001",
    ownerId: "usr_carla",
    amountCents: 39_000,
    probability: 12,
    expectedCloseDays: 1,
    product: "Mesa lateral Nórdica",
    stageEnteredDays: 0,
    createdDays: 1,
    tagIds: ["tag_carrinho", "tag_vip"],
  },
  {
    id: "dl_012",
    title: "Carrinho Talita — espelho orgânico",
    pipelineId: "pipe_matriculas",
    stageId: "stg_interesse",
    contactId: "cnt_003",
    ownerId: "usr_carla",
    amountCents: 52_000,
    probability: 12,
    expectedCloseDays: 2,
    product: "Espelho orgânico 90 cm",
    stageEnteredDays: 0,
    createdDays: 2,
  },
]);

const tasks = buildTasks(ORG_ID, [
  {
    id: "tsk_001",
    title: "Confirmar troca de endereço com a transportadora",
    contactId: "cnt_001",
    dueHours: 3,
    assigneeId: "usr_rafael",
    kind: "ligacao",
  },
  {
    id: "tsk_002",
    title: "Emitir cobrança da diferença do tapete (R$ 340)",
    contactId: "cnt_002",
    dueHours: 5,
    assigneeId: "usr_juliana",
    kind: "followup",
  },
  {
    id: "tsk_003",
    title: "Responder Procon com comprovante de estorno",
    contactId: "cnt_011",
    dueHours: 8,
    assigneeId: "usr_marina",
    kind: "documento",
  },
  {
    id: "tsk_004",
    title: "Enviar ficha cadastral assinada para análise de crédito",
    contactId: "cnt_005",
    dealId: "dl_001",
    dueHours: 26,
    assigneeId: "usr_bruno",
    kind: "email",
  },
  {
    id: "tsk_005",
    title: "Apresentar projeto de iluminação — Jurerê",
    contactId: "cnt_008",
    dealId: "dl_003",
    dueHours: 52,
    assigneeId: "usr_bruno",
    kind: "reuniao",
  },
  {
    id: "tsk_006",
    title: "Revisar régua de carrinho abandonado (queda de 6 p.p.)",
    contactId: "cnt_013",
    dueHours: 30,
    assigneeId: "usr_carla",
    kind: "followup",
  },
]);

/* Marketing ------------------------------------------------------------------------ */

const segments: Segment[] = [
  {
    id: "seg_carrinho_alto",
    organizationId: ORG_ID,
    name: "Carrinho acima de R$ 400 nas últimas 72 h",
    description: "Base da régua de recuperação. Recalculada a cada disparo.",
    match: "todas",
    dynamic: true,
    groups: [
      {
        id: "grp_1",
        match: "todas",
        rules: [
          {
            id: "r_1",
            field: "evento.checkout.abandoned",
            fieldLabel: "Abandonou checkout",
            operator: "nos_ultimos_dias",
            value: "3",
          },
          {
            id: "r_2",
            field: "carrinho.valor",
            fieldLabel: "Valor do carrinho",
            operator: "maior_que",
            value: "400",
          },
        ],
      },
    ],
    estimatedSize: 1840,
    eligibleSize: 1502,
    exclusions: [
      { reason: "Sem consentimento de marketing", count: 188 },
      { reason: "Limite de frequência (7 dias)", count: 96 },
      { reason: "Já comprou depois do abandono", count: 42 },
      { reason: "Telefone inválido", count: 12 },
    ],
    lastCalculatedAt: offsetIso({ hours: -1 }),
    createdAt: offsetIso({ days: -120 }),
    updatedAt: offsetIso({ hours: -1 }),
  },
  {
    id: "seg_lojistas_inativos",
    organizationId: ORG_ID,
    name: "Lojistas sem pedido há 90 dias",
    description: "Revendedores ativos que pararam de comprar no último trimestre.",
    match: "todas",
    dynamic: true,
    groups: [
      {
        id: "grp_1",
        match: "todas",
        rules: [
          {
            id: "r_1",
            field: "contato.tag",
            fieldLabel: "Tag",
            operator: "igual_a",
            value: "Lojista",
          },
          {
            id: "r_2",
            field: "pedido.ultimo",
            fieldLabel: "Último pedido (dias)",
            operator: "maior_que",
            value: "90",
          },
        ],
      },
    ],
    estimatedSize: 214,
    eligibleSize: 197,
    exclusions: [
      { reason: "Sem consentimento de marketing", count: 11 },
      { reason: "Crédito bloqueado", count: 6 },
    ],
    lastCalculatedAt: offsetIso({ hours: -9 }),
    createdAt: offsetIso({ days: -70 }),
    updatedAt: offsetIso({ hours: -9 }),
  },
];

const messageTemplates: MessageTemplate[] = [
  {
    id: "tpl_carrinho",
    organizationId: ORG_ID,
    name: "carrinho_abandonado_v4",
    channel: "whatsapp",
    category: "marketing",
    language: "pt_BR",
    status: "aprovado",
    headerText: "Seu carrinho ainda está aqui",
    body: "Oi, {{1}}! Separei o que você deixou no carrinho: {{2}}. Guardo por mais 24 horas — quer finalizar?",
    footerText: "Responda SAIR para não receber mais.",
    buttons: ["Finalizar compra", "Falar com atendente"],
    variables: ["contato.primeiro_nome", "carrinho.itens"],
    quality: "alta",
    createdAt: offsetIso({ days: -100 }),
    updatedAt: offsetIso({ days: -12 }),
  },
  {
    id: "tpl_rastreio",
    organizationId: ORG_ID,
    name: "pedido_a_caminho_v2",
    channel: "whatsapp",
    category: "utilidade",
    language: "pt_BR",
    status: "aprovado",
    body: "{{1}}, seu pedido {{2}} saiu para entrega. Acompanhe pelo código {{3}}.",
    variables: ["contato.primeiro_nome", "pedido.numero", "pedido.rastreio"],
    quality: "alta",
    createdAt: offsetIso({ days: -180 }),
    updatedAt: offsetIso({ days: -30 }),
  },
  {
    id: "tpl_lojista",
    organizationId: ORG_ID,
    name: "lojista_recompra_v1",
    channel: "whatsapp",
    category: "marketing",
    language: "pt_BR",
    status: "em_analise",
    body: "Olá, {{1}}! A nova coleção chegou e a tabela de lojista está com condição especial até {{2}}. Quer que eu monte uma sugestão de mix?",
    variables: ["contato.primeiro_nome", "promocao.validade"],
    createdAt: offsetIso({ days: -9 }),
    updatedAt: offsetIso({ days: -2 }),
  },
];

const campaigns = buildCampaigns(ORG_ID, [
  {
    id: "cmp_carrinho_agosto",
    name: "Recuperação de carrinho — agosto",
    objective: "Trazer de volta carrinhos acima de R$ 400 abandonados em 72 horas.",
    channel: "whatsapp",
    channelAccountId: "chan_wa_atendimento",
    segmentId: "seg_carrinho_alto",
    templateId: "tpl_carrinho",
    status: "enviando",
    ownerId: "usr_carla",
    startedHoursAgo: 3,
    utm: { source: "whatsapp", medium: "crm", campaign: "carrinho_agosto" },
    metrics: {
      eligible: 1502,
      excluded: 338,
      queued: 1502,
      sent: 980,
      delivered: 941,
      read: 712,
      replied: 128,
      converted: 74,
      failed: 39,
      optOuts: 9,
      costCents: 68_600,
    },
    deliveryTimeline: [
      { label: "08h", value: 210 },
      { label: "09h", value: 268 },
      { label: "10h", value: 251 },
      { label: "11h", value: 212 },
    ],
  },
  {
    id: "cmp_lojista_recompra",
    name: "Lojistas inativos — nova coleção",
    objective: "Reativar revendedores sem pedido há mais de 90 dias.",
    channel: "whatsapp",
    channelAccountId: "chan_wa_comercial",
    segmentId: "seg_lojistas_inativos",
    templateId: "tpl_lojista",
    status: "em_aprovacao",
    ownerId: "usr_bruno",
    scheduledInHours: 20,
    utm: { source: "whatsapp", medium: "crm", campaign: "lojista_recompra" },
    metrics: {
      eligible: 197,
      excluded: 17,
      queued: 0,
      sent: 0,
      delivered: 0,
      read: 0,
      replied: 0,
      converted: 0,
      failed: 0,
      optOuts: 0,
      costCents: 0,
    },
    throttle: { batchSize: 100, intervalMinutes: 15, maxPerHour: 400 },
  },
]);

const timeline = buildTimeline({
  orgId: ORG_ID,
  contacts,
  conversations: bundle.conversations,
  messages: bundle.messages,
  deals,
  pipelines,
  users,
  touches: [
    {
      contactId: "cnt_007",
      kind: "campanha",
      title: "Campanha recebida — Recuperação de carrinho",
      description: "Entregue e lida. Cliente voltou ao checkout em 12 minutos.",
      hoursAgo: 2,
      channel: "whatsapp",
      domainEvent: "campaign.delivered",
    },
    {
      contactId: "cnt_013",
      kind: "campanha",
      title: "Campanha recebida — Recuperação de carrinho",
      description: "Entregue, sem leitura registrada até agora.",
      hoursAgo: 3,
      channel: "whatsapp",
      domainEvent: "campaign.delivered",
    },
    {
      contactId: "cnt_001",
      kind: "automacao",
      title: "Automação executada — Pedido atrasado",
      description:
        'Regra "rastreio parado há mais de 48 h" abriu tarefa e marcou a conversa como alta.',
      hoursAgo: 1,
      domainEvent: "rule.executed",
    },
    {
      contactId: "cnt_011",
      kind: "automacao",
      title: "Jornada iniciada — Pós-Procon",
      description: "Entrada por evento complaint.registered. Versão publicada v2.",
      hoursAgo: 22,
      domainEvent: "journey.enrolled",
    },
    {
      contactId: "cnt_003",
      kind: "automacao",
      title: "Agente de IA — ocorrência de avaria aberta",
      description:
        "Ferramenta abrir_ocorrencia executada com confiança 0,91. Reposição sugerida ao atendente.",
      hoursAgo: 1,
      domainEvent: "agent.tool_executed",
    },
  ],
});

export const ecommerceOverlay: DemoOverlay = {
  meta: ECOMMERCE_META,
  organization,
  teams,
  users,
  queues,
  channelAccounts,
  tags,
  skills,
  closingReasons,
  customFields,
  cannedResponses,
  companies,
  contacts,
  conversations: bundle.conversations,
  messages: bundle.messages,
  internalNotes: bundle.internalNotes,
  timeline,
  pipelines,
  deals,
  tasks,
  segments,
  campaigns,
  messageTemplates,
};
