/**
 * Vertical de demonstração — imobiliária (Bandeira Imóveis).
 *
 * O que esta base demonstra e as outras não: **ciclo longo com proprietário do
 * contato valendo mais que rodízio**. No e-commerce, quem responde primeiro
 * atende; aqui o lead que volta em novembro precisa cair no corretor que o
 * levou para visitar em julho — trocar de corretor no meio destrói a única
 * vantagem que o time tem, que é lembrar do que a pessoa procura.
 *
 * É por isso que as filas usam `proprietario` com desempate por roleta, e é a
 * base certa para mostrar por que `DistributionModel` separa os modelos que
 * escolhem dos que apenas restringem.
 */

import type { DemoOverlay, DemoVerticalMeta } from "../types";
import type { Pipeline, Tag } from "../../types/crm";
import type { CannedResponse } from "../../types/inbox";
import type { MessageTemplate, Segment } from "../../types/marketing";
import type { Organization, Team } from "../../types/organization";
import { ORG_ID } from "../../mock/organization";
import { offsetIso } from "../../utils/datetime";
import {
  buildCampaigns,
  buildChannelAccounts,
  buildClosingReasons,
  buildCompanies,
  buildContacts,
  buildConversations,
  buildCustomFields,
  buildDeals,
  buildQueues,
  buildSkills,
  buildTasks,
  buildTimeline,
  buildUsers,
} from "../build";

const BRAND = "Bandeira Imóveis";

export const IMOBILIARIA_META: DemoVerticalMeta = {
  id: "imobiliaria",
  name: "Imobiliária",
  company: BRAND,
  tagline: "Vendas, locação e administração de carteira",
  description:
    "Ciclo longo, ticket alto e um lead que some por meses antes de voltar. Aqui o roteamento por " +
    "proprietário do contato é o que sustenta a relação, e o funil tem etapa jurídica — não é " +
    '"proposta enviada, negócio ganho".',
  hue: 30,
  highlights: [
    "Roteamento por proprietário: o lead volta para quem já o levou visitar.",
    "Funil com análise de crédito e etapa jurídica antes do ganho.",
    "Locação e venda como filas separadas, com SLA e escala diferentes.",
  ],
  channels: ["whatsapp", "webchat", "email", "instagram"],
  stats: [
    { label: "Leads / mês", value: "1,9 mil" },
    { label: "Ciclo médio", value: "74 dias" },
    { label: "Visita → proposta", value: "23%" },
  ],
};

const organization: Organization = {
  id: ORG_ID,
  name: BRAND,
  slug: "bandeira-imoveis",
  brandColor: "#102850",
  timezone: "America/Sao_Paulo",
};

const teams: Team[] = [
  { id: "team_comercial", organizationId: ORG_ID, name: "Vendas" },
  { id: "team_atendimento", organizationId: ORG_ID, name: "Locação" },
  { id: "team_aluno", organizationId: ORG_ID, name: "Administração de carteira" },
  { id: "team_marketing", organizationId: ORG_ID, name: "Marketing e captação" },
];

const skills = buildSkills(ORG_ID, [
  {
    key: "venda_alto_padrao",
    label: "Venda — alto padrão",
    description: "Imóveis acima de R$ 1,5 milhão.",
    hue: 30,
  },
  {
    key: "venda_economico",
    label: "Venda — econômico",
    description: "Minha Casa Minha Vida e financiamento Caixa.",
    hue: 100,
  },
  {
    key: "locacao",
    label: "Locação",
    description: "Contrato, garantia, vistoria e reajuste.",
    hue: 200,
  },
  {
    key: "credito",
    label: "Crédito imobiliário",
    description: "Simulação, aprovação e cartório.",
    hue: 262,
  },
  {
    key: "carteira",
    label: "Administração de carteira",
    description: "Repasse ao proprietário, manutenção e inadimplência.",
    hue: 160,
  },
]);

const queues = buildQueues(ORG_ID, [
  {
    id: "queue_comercial",
    name: "Vendas — leads de portal",
    description: "Leads de portais, site e anúncio pago interessados em comprar.",
    channels: ["whatsapp", "webchat", "instagram", "form"],
    teamId: "team_comercial",
    firstResponseSlaMinutes: 5,
    resolutionSlaMinutes: 480,
    color: "30",
    scheduleId: "sched_estendido",
    distribution: {
      // Proprietário primeiro: o lead que volta reencontra quem já o atendeu.
      // Sem dono, roleta — e nunca menor carga, que concentraria o lead novo em
      // quem acabou de perder um negócio.
      model: "proprietario",
      tiebreak: "roleta",
      delivery: "oferta",
      offerTimeoutSeconds: 45,
      maxOffers: 4,
    },
  },
  {
    id: "queue_matriculas",
    name: "Locação — interessados",
    description: "Visita, documentação, garantia locatícia e assinatura.",
    channels: ["whatsapp", "webchat", "email"],
    teamId: "team_atendimento",
    firstResponseSlaMinutes: 15,
    resolutionSlaMinutes: 480,
    color: "200",
    distribution: {
      model: "habilidade",
      tiebreak: "menor_carga",
      delivery: "direta",
      requiredSkills: ["locacao"],
    },
  },
  {
    id: "queue_regularizacao",
    name: "Carteira — inquilinos e proprietários",
    description: "Manutenção, repasse, reajuste, rescisão e inadimplência.",
    channels: ["whatsapp", "email"],
    teamId: "team_aluno",
    firstResponseSlaMinutes: 60,
    resolutionSlaMinutes: 2880,
    color: "160",
    distribution: {
      model: "proprietario",
      tiebreak: "menor_carga",
      delivery: "direta",
      requireAvailable: false,
    },
  },
  {
    id: "queue_fiscal",
    name: "Crédito e cartório",
    description: "Simulação, aprovação de financiamento, ITBI e escritura.",
    channels: ["whatsapp", "email"],
    teamId: "team_comercial",
    firstResponseSlaMinutes: 30,
    resolutionSlaMinutes: 1440,
    color: "262",
    distribution: {
      model: "habilidade",
      tiebreak: "menor_carga",
      delivery: "oferta",
      offerTimeoutSeconds: 90,
      requiredSkills: ["credito"],
    },
  },
]);

const channelAccounts = buildChannelAccounts(ORG_ID, [
  {
    id: "chan_wa_comercial",
    kind: "whatsapp",
    label: "WhatsApp Vendas",
    address: "+556232100400",
    queueId: "queue_comercial",
    qualityRating: "alta",
    dailyLimit: 10000,
    sentToday: 1240,
  },
  {
    id: "chan_wa_atendimento",
    kind: "whatsapp",
    label: "WhatsApp Locação",
    address: "+556232100410",
    queueId: "queue_matriculas",
    qualityRating: "media",
    dailyLimit: 10000,
    sentToday: 880,
  },
  {
    id: "chan_email_atendimento",
    kind: "email",
    label: "carteira@bandeiraimoveis.com.br",
    address: "carteira@bandeiraimoveis.com.br",
    queueId: "queue_regularizacao",
  },
  {
    id: "chan_instagram",
    kind: "instagram",
    label: "@bandeiraimoveis",
    address: "bandeiraimoveis",
    queueId: "queue_comercial",
  },
]);

const tags: Tag[] = [
  { id: "tag_alto_padrao", name: "Alto padrão", hue: 30 },
  { id: "tag_financiamento", name: "Financiamento", hue: 262 },
  { id: "tag_locacao", name: "Locação", hue: 200 },
  { id: "tag_proprietario", name: "Proprietário", hue: 160 },
  { id: "tag_visita_agendada", name: "Visita agendada", hue: 100 },
  { id: "tag_investidor", name: "Investidor", hue: 45 },
  { id: "tag_inadimplente", name: "Inadimplente", hue: 0 },
  { id: "tag_portal", name: "Lead de portal", hue: 218 },
  { id: "tag_indicacao", name: "Indicação", hue: 174 },
  { id: "tag_urgente", name: "Urgente", hue: 12 },
];

const closingReasons = buildClosingReasons(ORG_ID, [
  {
    key: "visita_realizada",
    label: "Visita realizada",
    description: "Cliente conheceu o imóvel e segue no funil.",
    resolved: true,
  },
  {
    key: "proposta_aceita",
    label: "Proposta aceita",
    description: "Proposta assinada pelas duas partes.",
    resolved: true,
  },
  {
    key: "contrato_assinado",
    label: "Contrato assinado",
    description: "Locação ou venda concluída em cartório.",
    resolved: true,
  },
  {
    key: "chamado_resolvido",
    label: "Chamado da carteira resolvido",
    description: "Manutenção concluída ou repasse regularizado.",
    resolved: true,
  },
  {
    key: "fora_do_perfil",
    label: "Fora do perfil",
    description: "Faixa de valor ou região que não trabalhamos.",
    resolved: false,
    requiresNote: true,
  },
  {
    key: "credito_negado",
    label: "Crédito negado",
    description: "Financiamento reprovado pelo banco.",
    resolved: false,
    requiresNote: true,
  },
]);

const customFields = buildCustomFields(ORG_ID, [
  {
    key: "faixa_valor",
    label: "Faixa de valor",
    description: "Orçamento declarado pelo interessado.",
    entity: "contato",
    type: "selecao",
    options: ["Até R$ 300 mil", "R$ 300 a 700 mil", "R$ 700 mil a 1,5 mi", "Acima de R$ 1,5 mi"],
  },
  {
    key: "regiao_interesse",
    label: "Região de interesse",
    description: "Bairros que o cliente aceita.",
    entity: "contato",
    type: "texto",
  },
  {
    key: "financiamento",
    label: "Precisa de financiamento",
    description: "Compra à vista ou com crédito imobiliário.",
    entity: "contato",
    type: "booleano",
  },
  {
    key: "codigo_imovel",
    label: "Código do imóvel",
    description: "Imóvel de origem do contato.",
    entity: "negocio",
    type: "texto",
  },
]);

const cannedResponses: CannedResponse[] = [
  {
    id: "canned_visita",
    organizationId: ORG_ID,
    shortcut: "/visita",
    title: "Agendar visita",
    body: "Consigo agendar a visita ao imóvel {{imovel.codigo}} para {{visita.opcoes}}. Qual horário fica melhor para você?",
    channels: ["whatsapp", "webchat"],
  },
  {
    id: "canned_docs_locacao",
    organizationId: ORG_ID,
    shortcut: "/docs",
    title: "Documentos para locação",
    body: "Para a análise cadastral preciso de: RG e CPF, comprovante de renda dos últimos 3 meses e comprovante de residência atual.",
    channels: ["whatsapp", "email"],
  },
  {
    id: "canned_garantia",
    organizationId: ORG_ID,
    shortcut: "/garantia",
    title: "Modalidades de garantia",
    body: "Trabalhamos com três garantias: fiador com imóvel próprio, seguro-fiança e caução de 3 aluguéis. Qual delas faz mais sentido para você?",
    channels: ["whatsapp", "email", "webchat"],
  },
  {
    id: "canned_simulacao",
    organizationId: ORG_ID,
    shortcut: "/simulacao",
    title: "Simulação de financiamento",
    body: "Com entrada de {{credito.entrada}} e prazo de {{credito.prazo}} anos, a parcela inicial fica em torno de {{credito.parcela}}. Posso enviar a simulação oficial do banco?",
    channels: ["whatsapp", "email"],
  },
  {
    id: "canned_repasse",
    organizationId: ORG_ID,
    shortcut: "/repasse",
    title: "Repasse ao proprietário",
    body: "O repasse do mês é feito até o 10º dia útil, após a compensação do aluguel. O extrato detalhado fica disponível no portal do proprietário.",
    channels: ["whatsapp", "email"],
  },
];

const users = buildUsers(ORG_ID, [
  {
    id: "usr_alex",
    name: "Cláudio Bandeira",
    email: "claudio.bandeira@bandeiraimoveis.com.br",
    role: "admin_empresa",
    teamIds: ["team_comercial", "team_aluno"],
    presence: "disponivel",
    capacity: 4,
    hue: 30,
    skills: ["venda_alto_padrao", "credito"],
  },
  {
    id: "usr_marina",
    name: "Marina Duarte",
    email: "marina.duarte@bandeiraimoveis.com.br",
    role: "gestor_comercial",
    teamIds: ["team_comercial"],
    presence: "disponivel",
    capacity: 6,
    hue: 218,
    skills: ["venda_alto_padrao", "venda_economico"],
  },
  {
    id: "usr_rafael",
    name: "Élton Ribas",
    email: "elton.ribas@bandeiraimoveis.com.br",
    role: "atendente",
    teamIds: ["team_comercial"],
    presence: "disponivel",
    capacity: 8,
    hue: 100,
    skills: ["venda_economico", "credito"],
    scheduleId: "sched_estendido",
  },
  {
    id: "usr_juliana",
    name: "Vanessa Curi",
    email: "vanessa.curi@bandeiraimoveis.com.br",
    role: "atendente",
    teamIds: ["team_atendimento"],
    presence: "disponivel",
    capacity: 7,
    hue: 200,
    skills: ["locacao"],
  },
  {
    id: "usr_bruno",
    name: "Sérgio Toledo",
    email: "sergio.toledo@bandeiraimoveis.com.br",
    role: "gestor_atendimento",
    teamIds: ["team_atendimento", "team_aluno"],
    presence: "ocupado",
    capacity: 5,
    hue: 160,
    skills: ["locacao", "carteira"],
    acceptingNew: false,
  },
  {
    id: "usr_carla",
    name: "Isadora Pinho",
    email: "isadora.pinho@bandeiraimoveis.com.br",
    role: "marketing",
    teamIds: ["team_marketing"],
    presence: "ausente",
    capacity: 3,
    hue: 340,
    skills: [],
  },
  {
    id: "usr_diego",
    name: "Alexandre Mota",
    email: "alexandre.mota@bandeiraimoveis.com.br",
    role: "atendente",
    teamIds: ["team_aluno"],
    presence: "offline",
    capacity: 6,
    hue: 262,
    skills: ["carteira"],
    scheduleId: "sched_estendido",
  },
]);

const companies = buildCompanies(ORG_ID, [
  {
    id: "cmp_001",
    name: "Construtora Alto Cerrado",
    document: "26.114.882/0001-45",
    segment: "Incorporadora",
    city: "Goiânia",
    state: "GO",
    contactsCount: 3,
    createdDays: 520,
    updatedDays: 5,
  },
  {
    id: "cmp_002",
    name: "Fundo Patrimonial Sete Lagoas",
    document: "39.001.774/0001-12",
    segment: "Investidor institucional",
    city: "Belo Horizonte",
    state: "MG",
    contactsCount: 2,
    createdDays: 300,
    updatedDays: 2,
  },
  {
    id: "cmp_003",
    name: "Rede Farma Popular",
    document: "18.552.003/0001-90",
    segment: "Varejo — locação comercial",
    city: "Goiânia",
    state: "GO",
    contactsCount: 2,
    createdDays: 210,
    updatedDays: 9,
  },
  {
    id: "cmp_004",
    name: "Condomínio Parque das Águas",
    document: "11.998.220/0001-33",
    segment: "Condomínio",
    city: "Aparecida de Goiânia",
    state: "GO",
    contactsCount: 2,
    createdDays: 400,
    updatedDays: 1,
  },
  {
    id: "cmp_005",
    name: "Escritório Vasconcelos Advogados",
    document: "63.221.005/0001-77",
    segment: "Serviços — locação comercial",
    city: "Goiânia",
    state: "GO",
    contactsCount: 1,
    createdDays: 130,
    updatedDays: 14,
  },
  {
    id: "cmp_006",
    name: "Agro Cerrado Participações",
    document: "72.880.114/0001-06",
    segment: "Agronegócio — investidor",
    city: "Rio Verde",
    state: "GO",
    contactsCount: 1,
    createdDays: 80,
    updatedDays: 6,
  },
]);

const contacts = buildContacts(ORG_ID, BRAND, [
  {
    id: "cnt_001",
    name: "Rodrigo Malafaia",
    email: "rodrigo.malafaia@gmail.com",
    phone: "+5562994120011",
    ownerId: "usr_marina",
    stage: "oportunidade",
    score: 84,
    origin: "form",
    campaign: "Portal — apartamento 3 quartos Setor Bueno",
    city: "Goiânia",
    state: "GO",
    tags: ["tag_portal", "tag_financiamento", "tag_visita_agendada"],
    hue: 30,
    lastDays: 0,
    createdDays: 52,
    fields: [
      { key: "faixa_valor", label: "Faixa de valor", value: "R$ 700 mil a 1,5 mi" },
      { key: "regiao_interesse", label: "Região de interesse", value: "Setor Bueno, Marista" },
    ],
  },
  {
    id: "cnt_002",
    name: "Carolina Bessa",
    email: "carolina.bessa@outlook.com",
    phone: "+5562996330087",
    ownerId: "usr_juliana",
    stage: "lead_qualificado",
    score: 62,
    origin: "whatsapp",
    city: "Goiânia",
    state: "GO",
    tags: ["tag_locacao"],
    hue: 200,
    lastDays: 0,
    createdDays: 9,
  },
  {
    id: "cnt_003",
    name: "Ubiratan Neves",
    email: "ubiratan.neves@altocerrado.com.br",
    phone: "+5562988220145",
    jobTitle: "Diretor comercial",
    companyId: "cmp_001",
    ownerId: "usr_alex",
    stage: "cliente",
    score: 91,
    origin: "email",
    city: "Goiânia",
    state: "GO",
    tags: ["tag_alto_padrao", "tag_investidor"],
    hue: 45,
    lastDays: 1,
    createdDays: 520,
  },
  {
    id: "cnt_004",
    name: "Patrícia Lemes",
    email: "patricia.lemes@gmail.com",
    phone: "+5562993410077",
    ownerId: "usr_rafael",
    stage: "oportunidade",
    score: 70,
    origin: "webchat",
    campaign: "Google Ads — MCMV Goiânia",
    city: "Aparecida de Goiânia",
    state: "GO",
    tags: ["tag_financiamento"],
    hue: 100,
    lastDays: 0,
    createdDays: 21,
    fields: [{ key: "faixa_valor", label: "Faixa de valor", value: "Até R$ 300 mil" }],
  },
  {
    id: "cnt_005",
    name: "Emerson Kalil",
    email: "emerson.kalil@setelagoas.fund.br",
    phone: "+5531984120033",
    jobTitle: "Gestor",
    companyId: "cmp_002",
    ownerId: "usr_alex",
    stage: "oportunidade",
    score: 79,
    origin: "email",
    city: "Belo Horizonte",
    state: "MG",
    tags: ["tag_investidor", "tag_alto_padrao"],
    hue: 262,
    lastDays: 2,
    createdDays: 60,
  },
  {
    id: "cnt_006",
    name: "Silvia Rondon",
    email: "silvia.rondon@gmail.com",
    phone: "+5562995870021",
    ownerId: "usr_diego",
    stage: "cliente",
    score: 48,
    origin: "whatsapp",
    city: "Goiânia",
    state: "GO",
    tags: ["tag_proprietario"],
    hue: 160,
    lastDays: 1,
    createdDays: 700,
  },
  {
    id: "cnt_007",
    name: "Márcio Zampieri",
    email: "marcio.zampieri@farmapopular.com.br",
    phone: "+5562987660019",
    jobTitle: "Gerente de expansão",
    companyId: "cmp_003",
    ownerId: "usr_bruno",
    stage: "oportunidade",
    score: 73,
    origin: "whatsapp",
    city: "Goiânia",
    state: "GO",
    tags: ["tag_locacao"],
    hue: 174,
    lastDays: 1,
    createdDays: 30,
  },
  {
    id: "cnt_008",
    name: "Denise Fiuza",
    email: "denise.fiuza@gmail.com",
    phone: "+5562991200064",
    ownerId: "usr_juliana",
    stage: "cliente",
    score: 55,
    origin: "whatsapp",
    city: "Goiânia",
    state: "GO",
    tags: ["tag_locacao", "tag_inadimplente"],
    hue: 0,
    lastDays: 2,
    createdDays: 380,
  },
  {
    id: "cnt_009",
    name: "Tarcísio Vilar",
    email: "tarcisio.vilar@vasconcelosadv.com.br",
    phone: "+5562994520188",
    jobTitle: "Sócio",
    companyId: "cmp_005",
    ownerId: "usr_bruno",
    stage: "cliente",
    score: 66,
    origin: "email",
    city: "Goiânia",
    state: "GO",
    tags: ["tag_locacao"],
    hue: 218,
    lastDays: 5,
    createdDays: 130,
  },
  {
    id: "cnt_010",
    name: "Heloísa Bacelar",
    email: "heloisa.bacelar@gmail.com",
    phone: "+5562988110052",
    ownerId: "usr_diego",
    stage: "cliente",
    score: 60,
    origin: "phone",
    city: "Goiânia",
    state: "GO",
    tags: ["tag_proprietario"],
    hue: 280,
    lastDays: 0,
    createdDays: 900,
  },
  {
    id: "cnt_011",
    name: "Gilmar Peixoto",
    email: "gilmar.peixoto@agrocerrado.com.br",
    phone: "+5564993330091",
    jobTitle: "Sócio-administrador",
    companyId: "cmp_006",
    ownerId: "usr_marina",
    stage: "lead_qualificado",
    score: 68,
    origin: "instagram",
    campaign: "Instagram — lançamento Vertice",
    city: "Rio Verde",
    state: "GO",
    tags: ["tag_investidor", "tag_alto_padrao"],
    hue: 45,
    lastDays: 3,
    createdDays: 18,
  },
  {
    id: "cnt_012",
    name: "Nathália Quintela",
    email: "nathalia.quintela@gmail.com",
    phone: "+5562991440076",
    ownerId: "usr_rafael",
    stage: "lead",
    score: 31,
    origin: "instagram",
    campaign: "Instagram — lançamento Vertice",
    city: "Goiânia",
    state: "GO",
    tags: ["tag_portal"],
    hue: 340,
    lastDays: 4,
    createdDays: 5,
  },
  {
    id: "cnt_013",
    name: "Osmar Bringel",
    email: "osmar.bringel@parquedasaguas.com.br",
    phone: "+5562994880023",
    jobTitle: "Síndico",
    companyId: "cmp_004",
    ownerId: "usr_diego",
    stage: "cliente",
    score: 52,
    origin: "email",
    city: "Aparecida de Goiânia",
    state: "GO",
    tags: ["tag_proprietario"],
    hue: 160,
    lastDays: 1,
    createdDays: 400,
  },
  {
    id: "cnt_014",
    name: "Rodrigo M. Malafaia",
    email: "rodrigo.malafaia@gmail.com",
    phone: "+5562994120011",
    ownerId: "usr_rafael",
    stage: "lead",
    score: 18,
    origin: "webchat",
    city: "Goiânia",
    state: "GO",
    tags: [],
    hue: 30,
    lastDays: 60,
    createdDays: 120,
    duplicateOf: "cnt_001",
  },
]);

const bundle = buildConversations(ORG_ID, queues, [
  {
    id: "cnv_001",
    contactId: "cnt_001",
    channel: "whatsapp",
    channelAccountId: "chan_wa_comercial",
    queueId: "queue_comercial",
    assigneeId: "usr_marina",
    state: "em_atendimento",
    subject: "Proposta pelo apartamento do Setor Bueno",
    priority: "alta",
    tagIds: ["tag_financiamento", "tag_visita_agendada"],
    unreadCount: 0,
    openedMinutesAgo: 180,
    firstRespondedMinutesAgo: 172,
    messages: [
      {
        from: "contato",
        authorLabel: "Rodrigo Malafaia",
        body: "Marina, conversei com minha esposa. Vamos fazer proposta de R$ 880 mil no apartamento AP-2214, com 30% de entrada.",
        minutesAgo: 180,
      },
      {
        from: "agente",
        authorId: "usr_marina",
        authorLabel: "Marina Duarte",
        body: "Ótima notícia, Rodrigo! Vou levar ao proprietário hoje ainda. O pedido é R$ 940 mil, então a chance de contraproposta existe — você toparia até quanto?",
        minutesAgo: 172,
        status: "lida",
      },
      {
        from: "contato",
        authorLabel: "Rodrigo Malafaia",
        body: "Até 900 eu vou. Acima disso a parcela do financiamento aperta.",
        minutesAgo: 160,
      },
      {
        from: "agente",
        authorId: "usr_marina",
        authorLabel: "Marina Duarte",
        body: "Perfeito. Já pedi a simulação atualizada com a Caixa para levarmos junto — proposta com crédito pré-aprovado costuma destravar a negociação.",
        minutesAgo: 150,
        status: "lida",
      },
    ],
    notes: [
      {
        authorId: "usr_marina",
        authorLabel: "Marina Duarte",
        body: "Proprietário já recusou 870 em junho. Vou apresentar 880 com pré-aprovação em mãos e prazo de resposta de 48 h.",
        minutesAgo: 140,
        mentions: ["usr_alex"],
      },
    ],
  },
  {
    id: "cnv_002",
    contactId: "cnt_002",
    channel: "whatsapp",
    channelAccountId: "chan_wa_atendimento",
    queueId: "queue_matriculas",
    assigneeId: "usr_juliana",
    state: "aguardando_cliente",
    subject: "Documentação para locação — Res. Vila Nova",
    priority: "normal",
    tagIds: ["tag_locacao"],
    unreadCount: 0,
    openedMinutesAgo: 420,
    firstRespondedMinutesAgo: 410,
    messages: [
      {
        from: "contato",
        authorLabel: "Carolina Bessa",
        body: "Gostei do apartamento que visitei ontem. O que preciso mandar para fechar?",
        minutesAgo: 420,
      },
      {
        from: "agente",
        authorId: "usr_juliana",
        authorLabel: "Vanessa Curi",
        body: "Que bom, Carolina! Preciso de RG, CPF, comprovante de renda dos últimos 3 meses e comprovante de residência. A garantia pode ser seguro-fiança, fiador ou caução de 3 aluguéis.",
        minutesAgo: 410,
        status: "lida",
      },
      {
        from: "agente",
        authorId: "usr_juliana",
        authorLabel: "Vanessa Curi",
        body: "Assim que chegar, a análise sai em até 48 horas úteis.",
        minutesAgo: 409,
        status: "entregue",
      },
    ],
  },
  {
    id: "cnv_003",
    contactId: "cnt_004",
    channel: "webchat",
    channelAccountId: "chan_wa_comercial",
    queueId: "queue_fiscal",
    state: "em_triagem",
    subject: "Simulação de financiamento — MCMV",
    priority: "normal",
    tagIds: ["tag_financiamento"],
    unreadCount: 1,
    openedMinutesAgo: 26,
    handoffSummary:
      "Interessada em imóvel de R$ 265 mil, renda familiar declarada de R$ 4.200. O assistente rodou a faixa do programa e parou antes de afirmar aprovação — condição de crédito é resposta do banco, não nossa.",
    botSessionId: "bot_sess_7712",
    messages: [
      {
        from: "contato",
        authorLabel: "Patrícia Lemes",
        body: "Consigo financiar um apartamento de 265 mil ganhando 4.200 com meu marido?",
        minutesAgo: 26,
      },
      {
        from: "bot",
        authorLabel: "Assistente Bandeira",
        body: "Com renda familiar de R$ 4.200 vocês se enquadram na Faixa 3 do programa, que costuma financiar até 80% do valor. A aprovação em si é do banco — vou chamar alguém do time para fazer a simulação oficial com você.",
        minutesAgo: 25,
        status: "entregue",
      },
    ],
  },
  {
    id: "cnv_004",
    contactId: "cnt_008",
    channel: "whatsapp",
    channelAccountId: "chan_wa_atendimento",
    queueId: "queue_regularizacao",
    assigneeId: "usr_bruno",
    state: "em_atendimento",
    subject: "Aluguel de agosto em atraso",
    priority: "alta",
    tagIds: ["tag_inadimplente", "tag_locacao"],
    unreadCount: 0,
    openedMinutesAgo: 1200,
    firstRespondedMinutesAgo: 1180,
    messages: [
      {
        from: "contato",
        authorLabel: "Denise Fiuza",
        body: "Sérgio, o aluguel desse mês vai atrasar. Recebo dia 15, consigo pagar tudo com os juros nesse dia.",
        minutesAgo: 1200,
      },
      {
        from: "agente",
        authorId: "usr_bruno",
        authorLabel: "Sérgio Toledo",
        body: "Obrigado por avisar antes, Denise — isso muda tudo. Vou registrar o acordo para 15/08 com a multa contratual e suspender a régua de cobrança até lá.",
        minutesAgo: 1180,
        status: "lida",
      },
    ],
    notes: [
      {
        authorId: "usr_bruno",
        authorLabel: "Sérgio Toledo",
        body: "Primeira ocorrência em 3 anos de contrato. Avisei a proprietária e ela concordou em esperar sem notificação extrajudicial.",
        minutesAgo: 1100,
      },
    ],
  },
  {
    id: "cnv_005",
    contactId: "cnt_005",
    channel: "email",
    channelAccountId: "chan_email_atendimento",
    queueId: "queue_comercial",
    assigneeId: "usr_alex",
    state: "aguardando_interno",
    subject: "Portfólio de 6 salas comerciais — Fundo Sete Lagoas",
    priority: "alta",
    tagIds: ["tag_investidor", "tag_alto_padrao"],
    unreadCount: 0,
    openedMinutesAgo: 2600,
    firstRespondedMinutesAgo: 2580,
    messages: [
      {
        from: "contato",
        authorLabel: "Emerson Kalil",
        body: "Cláudio, o comitê aprovou avaliar o portfólio. Precisamos da matrícula atualizada e do histórico de vacância dos últimos 24 meses das 6 salas.",
        minutesAgo: 2600,
      },
      {
        from: "agente",
        authorId: "usr_alex",
        authorLabel: "Cláudio Bandeira",
        body: "Emerson, já solicitei as matrículas no cartório e o histórico de vacância está sendo consolidado pela administração de carteira. Envio o dossiê completo até quinta.",
        minutesAgo: 2580,
        status: "lida",
      },
    ],
    notes: [
      {
        authorId: "usr_alex",
        authorLabel: "Cláudio Bandeira",
        body: "Duas das seis salas tiveram 7 meses de vacância em 2025. Melhor apresentar o dado com o plano de reposicionamento junto, não depois.",
        minutesAgo: 2400,
        mentions: ["usr_diego"],
      },
    ],
  },
  {
    id: "cnv_006",
    contactId: "cnt_010",
    channel: "whatsapp",
    channelAccountId: "chan_wa_atendimento",
    queueId: "queue_regularizacao",
    assigneeId: "usr_diego",
    state: "nova",
    subject: "Infiltração no imóvel alugado da Rua 24",
    priority: "urgente",
    tagIds: ["tag_proprietario", "tag_urgente"],
    unreadCount: 2,
    openedMinutesAgo: 15,
    messages: [
      {
        from: "contato",
        authorLabel: "Heloísa Bacelar",
        body: "A inquilina me ligou dizendo que tem infiltração no teto do quarto. Isso é por minha conta ou dela?",
        minutesAgo: 15,
      },
      {
        from: "contato",
        authorLabel: "Heloísa Bacelar",
        body: "Ela mandou foto, parece vir do apartamento de cima.",
        minutesAgo: 14,
      },
    ],
  },
  {
    id: "cnv_007",
    contactId: "cnt_007",
    channel: "whatsapp",
    channelAccountId: "chan_wa_atendimento",
    queueId: "queue_matriculas",
    assigneeId: "usr_bruno",
    state: "resolvida",
    subject: "Ponto comercial no Setor Oeste — proposta aceita",
    priority: "normal",
    tagIds: ["tag_locacao"],
    unreadCount: 0,
    openedMinutesAgo: 5800,
    firstRespondedMinutesAgo: 5790,
    satisfactionScore: 4,
    messages: [
      {
        from: "contato",
        authorLabel: "Márcio Zampieri",
        body: "O proprietário aceitou os R$ 12 mil com carência de 45 dias para obra?",
        minutesAgo: 5800,
      },
      {
        from: "agente",
        authorId: "usr_bruno",
        authorLabel: "Sérgio Toledo",
        body: "Aceitou, com carência de 30 dias. Já estou com a minuta do contrato pronta para assinatura digital.",
        minutesAgo: 5790,
        status: "lida",
      },
      {
        from: "contato",
        authorLabel: "Márcio Zampieri",
        body: "Fechado, pode mandar.",
        minutesAgo: 5780,
      },
    ],
  },
  {
    id: "cnv_008",
    contactId: "cnt_011",
    channel: "instagram",
    channelAccountId: "chan_instagram",
    queueId: "queue_comercial",
    state: "nova",
    subject: "Lançamento Vertice — valor da unidade de cobertura",
    priority: "normal",
    tagIds: ["tag_investidor", "tag_alto_padrao", "tag_portal"],
    unreadCount: 1,
    openedMinutesAgo: 6,
    messages: [
      {
        from: "contato",
        authorLabel: "Gilmar Peixoto",
        body: "Vi o lançamento Vertice. Ainda tem cobertura disponível? Qual o valor e a tabela de pagamento?",
        minutesAgo: 6,
      },
      {
        from: "bot",
        authorLabel: "Assistente Bandeira",
        body: "Temos duas coberturas disponíveis no Vertice, de 214 m² e 268 m². Os valores e a tabela variam por unidade — vou chamar um corretor para te passar agora.",
        minutesAgo: 5,
        status: "entregue",
      },
    ],
  },
]);

const pipelines: Pipeline[] = [
  {
    id: "pipe_vendas",
    organizationId: ORG_ID,
    name: "Vendas — residencial e investidor",
    description: "Do lead de portal à escritura, com etapa de crédito e jurídico.",
    stages: [
      {
        id: "stg_novo",
        name: "Lead novo",
        order: 1,
        probability: 8,
        stalledAfterDays: 2,
        kind: "aberta",
      },
      {
        id: "stg_qualificacao",
        name: "Perfil levantado",
        order: 2,
        probability: 20,
        stalledAfterDays: 5,
        kind: "aberta",
      },
      {
        id: "stg_visita",
        name: "Visita realizada",
        order: 3,
        probability: 40,
        stalledAfterDays: 10,
        kind: "aberta",
      },
      {
        id: "stg_proposta",
        name: "Proposta em análise",
        order: 4,
        probability: 60,
        stalledAfterDays: 7,
        kind: "aberta",
      },
      {
        id: "stg_credito",
        name: "Crédito e jurídico",
        order: 5,
        probability: 85,
        stalledAfterDays: 20,
        kind: "aberta",
      },
      {
        id: "stg_ganho",
        name: "Escritura assinada",
        order: 6,
        probability: 100,
        stalledAfterDays: 180,
        kind: "ganha",
      },
      {
        id: "stg_perdido",
        name: "Perdido",
        order: 7,
        probability: 0,
        stalledAfterDays: 180,
        kind: "perdida",
      },
    ],
    createdAt: offsetIso({ days: -600 }),
    updatedAt: offsetIso({ days: -22 }),
  },
  {
    id: "pipe_matriculas",
    organizationId: ORG_ID,
    name: "Locação",
    description: "Da visita à assinatura do contrato, com análise cadastral e garantia.",
    stages: [
      {
        id: "stg_interesse",
        name: "Interesse",
        order: 1,
        probability: 15,
        stalledAfterDays: 2,
        kind: "aberta",
      },
      {
        id: "stg_inscricao",
        name: "Visita agendada",
        order: 2,
        probability: 35,
        stalledAfterDays: 3,
        kind: "aberta",
      },
      {
        id: "stg_pagamento",
        name: "Análise cadastral",
        order: 3,
        probability: 70,
        stalledAfterDays: 3,
        kind: "aberta",
      },
      {
        id: "stg_matriculado",
        name: "Contrato assinado",
        order: 4,
        probability: 100,
        stalledAfterDays: 60,
        kind: "ganha",
      },
      {
        id: "stg_desistiu",
        name: "Desistiu",
        order: 5,
        probability: 0,
        stalledAfterDays: 60,
        kind: "perdida",
      },
    ],
    createdAt: offsetIso({ days: -420 }),
    updatedAt: offsetIso({ days: -8 }),
  },
];

const deals = buildDeals(ORG_ID, [
  {
    id: "dl_001",
    title: "AP-2214 Setor Bueno — Rodrigo Malafaia",
    pipelineId: "pipe_vendas",
    stageId: "stg_proposta",
    contactId: "cnt_001",
    ownerId: "usr_marina",
    amountCents: 88_000_000,
    probability: 60,
    expectedCloseDays: 10,
    product: "Apartamento 3 quartos, 112 m²",
    stageEnteredDays: 0,
    createdDays: 52,
    tagIds: ["tag_financiamento"],
  },
  {
    id: "dl_002",
    title: "Portfólio 6 salas — Fundo Sete Lagoas",
    pipelineId: "pipe_vendas",
    stageId: "stg_qualificacao",
    contactId: "cnt_005",
    companyId: "cmp_002",
    ownerId: "usr_alex",
    amountCents: 420_000_000,
    probability: 20,
    expectedCloseDays: 55,
    product: "Salas comerciais Ed. Órion",
    stageEnteredDays: 2,
    createdDays: 60,
    tagIds: ["tag_investidor"],
  },
  {
    id: "dl_003",
    title: "MCMV Aparecida — Patrícia Lemes",
    pipelineId: "pipe_vendas",
    stageId: "stg_credito",
    contactId: "cnt_004",
    ownerId: "usr_rafael",
    amountCents: 26_500_000,
    probability: 85,
    expectedCloseDays: 18,
    product: "Apartamento 2 quartos, 48 m²",
    stageEnteredDays: 1,
    createdDays: 21,
    tagIds: ["tag_financiamento"],
  },
  {
    id: "dl_004",
    title: "Cobertura Vertice — Gilmar Peixoto",
    pipelineId: "pipe_vendas",
    stageId: "stg_novo",
    contactId: "cnt_011",
    companyId: "cmp_006",
    ownerId: "usr_marina",
    amountCents: 195_000_000,
    probability: 8,
    expectedCloseDays: 90,
    product: "Cobertura 268 m²",
    stageEnteredDays: 0,
    createdDays: 18,
    tagIds: ["tag_alto_padrao"],
  },
  {
    id: "dl_005",
    title: "Casa Jardim Goiás — Ubiratan Neves",
    pipelineId: "pipe_vendas",
    stageId: "stg_ganho",
    contactId: "cnt_003",
    companyId: "cmp_001",
    ownerId: "usr_alex",
    amountCents: 165_000_000,
    probability: 100,
    expectedCloseDays: -12,
    product: "Casa 4 suítes, 380 m²",
    stageEnteredDays: 12,
    createdDays: 210,
    tagIds: ["tag_alto_padrao"],
  },
  {
    id: "dl_006",
    title: "Terreno Rio Verde — investidor",
    pipelineId: "pipe_vendas",
    stageId: "stg_perdido",
    contactId: "cnt_011",
    ownerId: "usr_rafael",
    amountCents: 72_000_000,
    probability: 0,
    expectedCloseDays: -30,
    product: "Terreno 1.200 m²",
    lostReason: "Comprador desistiu após laudo de drenagem do lote",
    stageEnteredDays: 30,
    createdDays: 150,
  },
  {
    id: "dl_007",
    title: "Locação Res. Vila Nova — Carolina Bessa",
    pipelineId: "pipe_matriculas",
    stageId: "stg_pagamento",
    contactId: "cnt_002",
    ownerId: "usr_juliana",
    amountCents: 280_000,
    probability: 70,
    expectedCloseDays: 3,
    product: "Apartamento 2 quartos — aluguel mensal",
    stageEnteredDays: 0,
    createdDays: 9,
    tagIds: ["tag_locacao"],
  },
  {
    id: "dl_008",
    title: "Ponto comercial Setor Oeste — Farma Popular",
    pipelineId: "pipe_matriculas",
    stageId: "stg_matriculado",
    contactId: "cnt_007",
    companyId: "cmp_003",
    ownerId: "usr_bruno",
    amountCents: 1_200_000,
    probability: 100,
    expectedCloseDays: -4,
    product: "Loja 180 m² — aluguel mensal",
    stageEnteredDays: 4,
    createdDays: 30,
  },
  {
    id: "dl_009",
    title: "Sala 704 Ed. Órion — Vasconcelos Advogados",
    pipelineId: "pipe_matriculas",
    stageId: "stg_inscricao",
    contactId: "cnt_009",
    companyId: "cmp_005",
    ownerId: "usr_juliana",
    amountCents: 620_000,
    probability: 35,
    expectedCloseDays: 8,
    product: "Sala comercial 62 m² — aluguel mensal",
    stageEnteredDays: 2,
    createdDays: 14,
  },
  {
    id: "dl_010",
    title: "Locação Rua 24 — renovação",
    pipelineId: "pipe_matriculas",
    stageId: "stg_interesse",
    contactId: "cnt_010",
    ownerId: "usr_diego",
    amountCents: 195_000,
    probability: 15,
    expectedCloseDays: 25,
    product: "Casa 3 quartos — renovação de contrato",
    stageEnteredDays: 1,
    createdDays: 20,
    tagIds: ["tag_proprietario"],
  },
  {
    id: "dl_011",
    title: "Locação Setor Marista — Nathália Quintela",
    pipelineId: "pipe_matriculas",
    stageId: "stg_desistiu",
    contactId: "cnt_012",
    ownerId: "usr_rafael",
    amountCents: 340_000,
    probability: 0,
    expectedCloseDays: -6,
    product: "Studio 38 m² — aluguel mensal",
    lostReason: "Não conseguiu fiador nem aprovou seguro-fiança",
    stageEnteredDays: 6,
    createdDays: 18,
  },
  {
    id: "dl_012",
    title: "Locação Parque das Águas — 2 unidades",
    pipelineId: "pipe_matriculas",
    stageId: "stg_pagamento",
    contactId: "cnt_013",
    companyId: "cmp_004",
    ownerId: "usr_diego",
    amountCents: 460_000,
    probability: 70,
    expectedCloseDays: 5,
    product: "Duas unidades — aluguel mensal",
    stageEnteredDays: 1,
    createdDays: 25,
  },
]);

const tasks = buildTasks(ORG_ID, [
  {
    id: "tsk_001",
    title: "Levar proposta de R$ 880 mil ao proprietário",
    contactId: "cnt_001",
    dealId: "dl_001",
    dueHours: 4,
    assigneeId: "usr_marina",
    kind: "ligacao",
  },
  {
    id: "tsk_002",
    title: "Abrir chamado de infiltração com o condomínio",
    contactId: "cnt_010",
    dueHours: 3,
    assigneeId: "usr_diego",
    kind: "followup",
  },
  {
    id: "tsk_003",
    title: "Consolidar histórico de vacância das 6 salas",
    contactId: "cnt_005",
    dealId: "dl_002",
    dueHours: 40,
    assigneeId: "usr_diego",
    kind: "documento",
  },
  {
    id: "tsk_004",
    title: "Enviar simulação oficial da Caixa — Patrícia",
    contactId: "cnt_004",
    dealId: "dl_003",
    dueHours: 22,
    assigneeId: "usr_rafael",
    kind: "email",
  },
  {
    id: "tsk_005",
    title: "Visita ao Vertice com Gilmar Peixoto",
    contactId: "cnt_011",
    dealId: "dl_004",
    dueHours: 54,
    assigneeId: "usr_marina",
    kind: "reuniao",
  },
  {
    id: "tsk_006",
    title: "Registrar acordo de pagamento em 15/08",
    contactId: "cnt_008",
    dueHours: 8,
    assigneeId: "usr_bruno",
    kind: "documento",
  },
]);

const segments: Segment[] = [
  {
    id: "seg_visitou_sem_proposta",
    organizationId: ORG_ID,
    name: "Visitou e não fez proposta em 15 dias",
    description: "Leads que conheceram imóvel e esfriaram — o ponto onde o funil mais vaza.",
    match: "todas",
    dynamic: true,
    groups: [
      {
        id: "grp_1",
        match: "todas",
        rules: [
          {
            id: "r_1",
            field: "negocio.etapa",
            fieldLabel: "Etapa do negócio",
            operator: "igual_a",
            value: "Visita realizada",
          },
          {
            id: "r_2",
            field: "negocio.dias_na_etapa",
            fieldLabel: "Dias na etapa",
            operator: "maior_que",
            value: "15",
          },
        ],
      },
    ],
    estimatedSize: 168,
    eligibleSize: 141,
    exclusions: [
      { reason: "Sem consentimento de marketing", count: 18 },
      { reason: "Limite de frequência (14 dias)", count: 9 },
    ],
    lastCalculatedAt: offsetIso({ hours: -3 }),
    createdAt: offsetIso({ days: -95 }),
    updatedAt: offsetIso({ hours: -3 }),
  },
  {
    id: "seg_proprietarios_vacancia",
    organizationId: ORG_ID,
    name: "Proprietários com imóvel vago há 60 dias",
    description: "Base da conversa de reposicionamento de preço.",
    match: "todas",
    dynamic: true,
    groups: [
      {
        id: "grp_1",
        match: "todas",
        rules: [
          {
            id: "r_1",
            field: "contato.tag",
            fieldLabel: "Tag",
            operator: "igual_a",
            value: "Proprietário",
          },
          {
            id: "r_2",
            field: "imovel.dias_vago",
            fieldLabel: "Dias vago",
            operator: "maior_que",
            value: "60",
          },
        ],
      },
    ],
    estimatedSize: 92,
    eligibleSize: 88,
    exclusions: [{ reason: "Sem consentimento de marketing", count: 4 }],
    lastCalculatedAt: offsetIso({ hours: -20 }),
    createdAt: offsetIso({ days: -60 }),
    updatedAt: offsetIso({ hours: -20 }),
  },
];

const messageTemplates: MessageTemplate[] = [
  {
    id: "tpl_pos_visita",
    organizationId: ORG_ID,
    name: "pos_visita_v3",
    channel: "whatsapp",
    category: "marketing",
    language: "pt_BR",
    status: "aprovado",
    body: "Oi, {{1}}! Passando para saber o que achou do {{2}}. Separei mais duas opções na mesma faixa, quer ver?",
    variables: ["contato.primeiro_nome", "imovel.descricao"],
    buttons: ["Ver opções", "Não tenho interesse"],
    quality: "alta",
    createdAt: offsetIso({ days: -150 }),
    updatedAt: offsetIso({ days: -20 }),
  },
  {
    id: "tpl_vacancia",
    organizationId: ORG_ID,
    name: "proprietario_vacancia_v2",
    channel: "whatsapp",
    category: "utilidade",
    language: "pt_BR",
    status: "aprovado",
    body: "{{1}}, seu imóvel {{2}} está anunciado há {{3}} dias com {{4}} visitas. Posso te mandar a análise de preço da região?",
    variables: [
      "contato.primeiro_nome",
      "imovel.codigo",
      "imovel.dias_anunciado",
      "imovel.visitas",
    ],
    quality: "media",
    createdAt: offsetIso({ days: -80 }),
    updatedAt: offsetIso({ days: -10 }),
  },
  {
    id: "tpl_lancamento",
    organizationId: ORG_ID,
    name: "lancamento_vertice_v1",
    channel: "whatsapp",
    category: "marketing",
    language: "pt_BR",
    status: "rejeitado",
    body: "{{1}}, o Vertice lançou! Unidades a partir de R$ 1,2 mi com 40% na obra. GARANTA JÁ A SUA!!!",
    variables: ["contato.primeiro_nome"],
    rejectionReason:
      "Uso de caixa alta e apelo de urgência em excesso, contra a política de marketing do provedor.",
    createdAt: offsetIso({ days: -14 }),
    updatedAt: offsetIso({ days: -12 }),
  },
];

const campaigns = buildCampaigns(ORG_ID, [
  {
    id: "cmp_pos_visita",
    name: "Pós-visita — retomada em 15 dias",
    objective: "Reativar quem visitou e não avançou, com duas opções alternativas.",
    channel: "whatsapp",
    channelAccountId: "chan_wa_comercial",
    segmentId: "seg_visitou_sem_proposta",
    templateId: "tpl_pos_visita",
    status: "enviando",
    ownerId: "usr_carla",
    startedHoursAgo: 2,
    utm: { source: "whatsapp", medium: "crm", campaign: "pos_visita" },
    metrics: {
      eligible: 141,
      excluded: 27,
      queued: 141,
      sent: 100,
      delivered: 97,
      read: 71,
      replied: 19,
      converted: 6,
      failed: 3,
      optOuts: 2,
      costCents: 7_000,
    },
    throttle: { batchSize: 50, intervalMinutes: 20, maxPerHour: 200 },
    deliveryTimeline: [
      { label: "14h", value: 50 },
      { label: "15h", value: 47 },
    ],
  },
  {
    id: "cmp_vacancia",
    name: "Proprietários — análise de preço",
    objective: "Abrir conversa de reposicionamento com quem está com imóvel parado.",
    channel: "whatsapp",
    channelAccountId: "chan_wa_atendimento",
    segmentId: "seg_proprietarios_vacancia",
    templateId: "tpl_vacancia",
    status: "rascunho",
    ownerId: "usr_bruno",
    utm: { source: "whatsapp", medium: "crm", campaign: "vacancia_agosto" },
    metrics: {
      eligible: 88,
      excluded: 4,
      queued: 0,
      sent: 0,
      delivered: 0,
      read: 0,
      replied: 0,
      converted: 0,
      failed: 0,
      optOuts: 0,
      costCents: 0,
    },
    throttle: { batchSize: 40, intervalMinutes: 30, maxPerHour: 120 },
  },
]);

const timeline = buildTimeline({
  orgId: ORG_ID,
  contacts,
  conversations: bundle.conversations,
  messages: bundle.messages,
  deals,
  pipelines,
  users,
  touches: [
    {
      contactId: "cnt_012",
      kind: "campanha",
      title: "Campanha recebida — Pós-visita",
      description: "Entregue e lida, sem resposta até agora.",
      hoursAgo: 2,
      channel: "whatsapp",
      domainEvent: "campaign.delivered",
    },
    {
      contactId: "cnt_011",
      kind: "campanha",
      title: "Campanha recebida — Lançamento Vertice",
      description: "Não enviada: template reprovado pelo provedor antes do disparo.",
      hoursAgo: 12,
      channel: "whatsapp",
      domainEvent: "campaign.blocked",
    },
    {
      contactId: "cnt_001",
      kind: "automacao",
      title: "Automação executada — Proposta registrada",
      description: "Tarefa criada para o gestor e negócio movido para Proposta em análise.",
      hoursAgo: 3,
      domainEvent: "rule.executed",
    },
    {
      contactId: "cnt_004",
      kind: "automacao",
      title: "Jornada iniciada — Crédito imobiliário",
      description:
        "Entrada por evento deal.stage_changed (Crédito e jurídico). Versão publicada v2.",
      hoursAgo: 24,
      domainEvent: "journey.enrolled",
    },
    {
      contactId: "cnt_008",
      kind: "automacao",
      title: "Régua de cobrança suspensa",
      description:
        "Acordo registrado para 15/08; a régua volta a rodar no dia 16 se não houver pagamento.",
      hoursAgo: 18,
      domainEvent: "rule.executed",
    },
  ],
});

export const imobiliariaOverlay: DemoOverlay = {
  meta: IMOBILIARIA_META,
  organization,
  teams,
  users,
  queues,
  channelAccounts,
  tags,
  skills,
  closingReasons,
  customFields,
  cannedResponses,
  companies,
  contacts,
  conversations: bundle.conversations,
  messages: bundle.messages,
  internalNotes: bundle.internalNotes,
  timeline,
  pipelines,
  deals,
  tasks,
  segments,
  campaigns,
  messageTemplates,
};
